// Code generated by cmd/shimgen; DO NOT EDIT.

// Package conversation is a compatibility shim.
//
// Deprecated: the implementation moved to internal/conversation. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package conversation

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/conversation"
)

type A2AMetadata = ipkg.A2AMetadata
type AgentMemory = ipkg.AgentMemory
type AppMode = ipkg.AppMode
type BlockType = ipkg.BlockType
type BlockedToolCall = ipkg.BlockedToolCall
type CompactionState = ipkg.CompactionState
type ContentBlock = ipkg.ContentBlock
type Conversation = ipkg.Conversation
type ConversationMetadata = ipkg.ConversationMetadata
type ConversationSummary = ipkg.ConversationSummary
type Edit = ipkg.Edit
type FileAccessEntry = ipkg.FileAccessEntry
type FileSnapshotEntry = ipkg.FileSnapshotEntry
type GroupState = ipkg.GroupState
type Message = ipkg.Message
type MessageBlock = ipkg.MessageBlock
type ModeContextSnapshot = ipkg.ModeContextSnapshot
type ModeState = ipkg.ModeState
type ModeTransition = ipkg.ModeTransition
type OperatingModeState = ipkg.OperatingModeState
type OperatingModeTransition = ipkg.OperatingModeTransition
type PlanArchiveEntry = ipkg.PlanArchiveEntry
type PlanContext = ipkg.PlanContext
type PromptArchiveEntry = ipkg.PromptArchiveEntry
type Reference = ipkg.Reference
type Role = ipkg.Role
type Status = ipkg.Status
type SteeringDecision = ipkg.SteeringDecision
type SubAgentActivity = ipkg.SubAgentActivity
type TaskEntry = ipkg.TaskEntry
type TokenUsage = ipkg.TokenUsage
type ToolCall = ipkg.ToolCall
type ToolError = ipkg.ToolError
type ToolResult = ipkg.ToolResult

const A2APersistedMetadataKey = ipkg.A2APersistedMetadataKey
const AppModeChat = ipkg.AppModeChat
const AppModeCode = ipkg.AppModeCode
const AppModeTagPrefix = ipkg.AppModeTagPrefix
const AppModeWork = ipkg.AppModeWork
const BlockTypeContent = ipkg.BlockTypeContent
const BlockTypeHookExecution = ipkg.BlockTypeHookExecution
const BlockTypeSubAgentActivity = ipkg.BlockTypeSubAgentActivity
const BlockTypeThinking = ipkg.BlockTypeThinking
const BlockTypeToolCall = ipkg.BlockTypeToolCall
const BlockTypeToolResult = ipkg.BlockTypeToolResult
const RoleAssistant = ipkg.RoleAssistant
const RolePeer = ipkg.RolePeer
const RoleSystem = ipkg.RoleSystem
const RoleTool = ipkg.RoleTool
const RoleUser = ipkg.RoleUser
const StatusActive = ipkg.StatusActive
const StatusArchived = ipkg.StatusArchived
const StatusCompleted = ipkg.StatusCompleted
const StatusFailed = ipkg.StatusFailed
const SummaryPreviewMaxLen = ipkg.SummaryPreviewMaxLen

var AppModeTag = ipkg.AppModeTag
var GenerateConversationPreview = ipkg.GenerateConversationPreview
var GetAppMode = ipkg.GetAppMode
var IsValidAppMode = ipkg.IsValidAppMode
var OrderBlocksForDisplay = ipkg.OrderBlocksForDisplay
var ParseAppModeTag = ipkg.ParseAppModeTag
var SetAppMode = ipkg.SetAppMode
