import { registerAutoSkills, type Config } from "../../autogenskills/src/index.ts";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import "../hook-state.ts";

/** Pi adapter for Swarm's stateful autogenerated-skills lifecycle. */
export interface AutoSkillsExtensionOptions extends Config {}

export function registerAutoSkillsExtension(pi: any, options: AutoSkillsExtensionOptions = {}) {
  const child = process.env.SWARM_CURATOR_CHILD === "1";
  const extensionPath = fileURLToPath(import.meta.url);
  const configuredDir = options.dir ?? process.env.SWARM_AUTOGEN_DIR;
  const dir = configuredDir?.trim() || join(process.env.HOME ?? process.cwd(), ".swarm", "skills", "autogen");
  const curatorRunner = options.curatorRunner ?? (!child && typeof pi.exec === "function"
    ? async (request: Parameters<NonNullable<Config["curatorRunner"]>>[0]) => {
      const result = await pi.exec("env", [
        `SWARM_AUTOGEN_MODE=manual`,
        `SWARM_AUTOGEN_DIR=${dir}`,
        `SWARM_AUTOGEN_PREVIEW=${request.preview ? "1" : "0"}`,
        "SWARM_AUTOGEN_REQUIRE_VIEW=1",
        "SWARM_AUTOGEN_ACCOUNTING_EXEMPT=1",
        "SWARM_CURATOR_CHILD=1",
        "pi",
        "--no-session",
        "--no-extensions",
        "--extension", extensionPath,
        "--no-skills",
        "--no-context-files",
        "--no-prompt-templates",
        "--tools", "SkillManage",
        "--mode", "text",
        "-p", request.prompt,
      ], { cwd: process.cwd(), timeout: request.timeoutMs });
      if (result.code !== 0 || result.killed) {
        throw new Error(`curator child failed (${result.killed ? "timeout" : `exit ${result.code}`}): ${result.stderr.trim()}`);
      }
      return { output: result.stdout.trim() };
    }
    : undefined);
  return registerAutoSkills(pi, {
    ...options,
    dir,
    previewOnly: options.previewOnly ?? process.env.SWARM_AUTOGEN_PREVIEW === "1",
    requireReadBeforeWrite: options.requireReadBeforeWrite ?? process.env.SWARM_AUTOGEN_REQUIRE_VIEW === "1",
    accountingExempt: options.accountingExempt ?? process.env.SWARM_AUTOGEN_ACCOUNTING_EXEMPT === "1",
    curatorRunner,
  });
}

export default function autogenskillsExtension(pi: any) {
  // Enable the Swarm lifecycle by default. Use SWARM_AUTOGEN_MODE=never to
  // disable it, or =manual to allow Skill/SkillManage without auto nudges.
  registerAutoSkillsExtension(pi, {
    mode: (process.env.SWARM_AUTOGEN_MODE as Config["mode"]) ?? "auto",
    dir: process.env.SWARM_AUTOGEN_DIR || undefined,
  });
}
