import { registerAutoSkills, type Config } from "../../autogenskills/src/index.ts";
import "../hook-state.ts";

/** Pi adapter for Swarm's stateful autogenerated-skills lifecycle. */
export interface AutoSkillsExtensionOptions extends Config {}

export function registerAutoSkillsExtension(pi: any, options: AutoSkillsExtensionOptions = {}) {
  return registerAutoSkills(pi, options);
}

export default function autogenskillsExtension(pi: any) {
  registerAutoSkillsExtension(pi, {
    mode: (process.env.SWARM_AUTOGEN_MODE as Config["mode"]) ?? "auto",
  });
}
