import { getSwarmSkillRegistry, type SkillLoaderOptions } from "../lib/swarm-skill-registry.ts";

export interface SwarmSkillsOptions extends SkillLoaderOptions { watch?: boolean; }

export function registerSwarmSkills(pi: any, options: SwarmSkillsOptions = {}) {
  // Normal operation includes installed, project, user, and autogenerated skills.
  // Closed mode remains explicit and only admits the configured CLI paths.
  const registry = getSwarmSkillRegistry(pi, { cwd: options.cwd ?? process.cwd(), ...options, closed: options.closed ?? (process.env.SWARM_SKILLS_CLOSED === "1") });
  let current = registry.refresh();
  const bridged: any[] = [];
  const originalRegister = pi.registerTool?.bind(pi);
  pi.registerTool = (tool: unknown) => { bridged.push(tool); originalRegister?.(tool); };
  (pi as any).codemodeTools = [...((pi as any).codemodeTools ?? []), ...bridged];
  const refresh = () => { current = registry.refresh(); };
  if (options.watch) registry.loader.watch(refresh);
  pi.on?.("session_start", refresh);
  // Prompt composition is owned by swarm-prompt.ts. This extension owns only
  // discovery, invocation, and the inspection command; registering another
  // systemPrompt writer here can overwrite the Forge assembly.
  pi.registerCommand?.("skill", { description: "List discovered Swarm skills and their sources", handler: async (_args: string, ctx: any) => {
    current = registry.refresh();
    const text = current.skills.map(s => `${s.name} [${s.source}] — ${s.description}`).join("\n") || "No skills discovered";
    ctx.ui?.notify?.(text, "info");
  }});
  pi.registerCommand?.("swarm-skills", { description: "List discovered Swarm skills", handler: async (args: string, ctx: any) => {
    current = registry.refresh();
    const requested = args.trim();
    const skill = requested ? registry.find(requested) : undefined;
    ctx.ui?.notify?.(skill ? `${skill.name} [${skill.source}]\n${skill.description}` : current.skills.map(s => `${s.name} [${s.source}] — ${s.description}`).join("\n") || "No skills discovered", "info");
  }});
  // The autogenskills extension owns the canonical model-facing `Skill` tool
  // and invokes its stateful manager. This extension must not register a second
  // tool with the same name; it only supplies the shared discovery registry and
  // the user-facing discovery commands.
  return { loader: registry.loader, registry, getResult: () => current };
}

export default function swarmSkillsExtension(pi: any) { return registerSwarmSkills(pi); }
