// Package presentationcontrol implements ADR-003's presentation control
// plane: a versioned JSON envelope, a preface-based negotiation mechanism
// that lets a single Unix-domain-socket listener coexist with the legacy
// binary automation protocol, and a minimal verb dispatcher.
//
// This package speaks ONLY the "presentation" plane (ADR-003's plane.verb
// namespacing table: "Presentation | Attached TUI server and live Bubble
// Tea model | Input injection, resize, image delivery, frame/state/field
// reads, UI diagnostics, SDK-event forwarding | Ownership of engine
// execution or A2A task state"). It intentionally does not know about the
// engine or peer-task planes described in the same ADR; a later phase that
// wants those planes on the same wire format defines its own envelope
// producers/consumers rather than extending this package's verb registry.
//
// See INDEX.md in this directory for the exact preface-disambiguation
// numeric argument, the chosen envelope-framing mechanism, and this
// phase's explicitly deferred scope.
package presentationcontrol

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"

	"github.com/Swarm-Code/mono/swarm-sdk/internal/attachcontract"
)

// Plane is the fixed plane identifier every Envelope produced by this
// package carries. ADR-003 requires "A verb MUST include a plane-specific
// namespace"; this package only ever speaks the presentation plane, so
// Plane is a constant rather than a caller-supplied value. A future phase
// that introduces additional planes on this wire format does so in its own
// package rather than parameterizing this one.
const Plane = "presentation"

// SchemaVersion is the schema_version this package stamps onto every
// Envelope it constructs via NewRequest and NewErrorResponse. It reuses
// attachcontract.Version's "major.minor" string encoding (ADR-004's
// version model) rather than redefining a parallel version type. Go does
// not allow a struct-valued package constant, so this is a var; callers
// MUST NOT mutate it.
var SchemaVersion = attachcontract.Version{Major: 1, Minor: 0}

// Envelope is the presentation-plane JSON-RPC-over-Unix-domain-socket
// message shape shared by requests and responses. Plane is always
// "presentation" this phase (ADR-003 plane.verb namespacing); Op is the
// verb (e.g. "presentation.ping"); SchemaVersion reuses attachcontract's
// major.minor string encoding; Payload carries the verb-specific request
// or response body as raw JSON so the envelope layer never needs to know
// concrete per-verb payload types; Error is populated instead of Payload
// on a failed request (see NewErrorResponse).
type Envelope struct {
	// SchemaVersion identifies the "major.minor" contract version this
	// envelope was produced under (attachcontract.Version's JSON string
	// encoding, e.g. "1.0").
	SchemaVersion attachcontract.Version `json:"schema_version"`
	// Plane is always "presentation" (see the package-level Plane
	// constant) this phase; ADR-003's plane.verb namespacing.
	Plane string `json:"plane"`
	// Op is the presentation-plane verb, namespaced as "presentation.*"
	// (e.g. "presentation.ping", "presentation.capabilities").
	Op string `json:"op"`
	// CorrelationID ties a response back to the request that produced it.
	// It is always generated by NewRequest using crypto/rand -- never a
	// counter or PID -- so correlation IDs are unguessable and safe to
	// treat as unique across concurrent callers and process restarts.
	CorrelationID string `json:"correlation_id"`
	// Payload is the verb-specific request or response body, encoded as
	// raw JSON. It is omitted entirely (not even "null") when the
	// envelope carries no payload, e.g. a request with no body needed or
	// an error response.
	Payload json.RawMessage `json:"payload,omitempty"`
	// Error is populated only on a failed response (see NewErrorResponse)
	// and is nil on every successful request or response.
	Error *EnvelopeError `json:"error,omitempty"`
}

// EnvelopeError is the structured error carried by a failed Envelope.
// Category is a stable, caller-comparable error category string (e.g.
// "malformed_envelope", "unknown_operation", "internal_error"); Message is
// a human-readable detail string that MUST NOT be relied upon
// programmatically.
type EnvelopeError struct {
	// Category is a stable, machine-comparable error category.
	Category string `json:"category"`
	// Message is a human-readable error detail.
	Message string `json:"message"`
}

// Capabilities is this endpoint's advertised presentation-plane
// capabilities. It is a type alias for attachcontract.CapabilityAdvertisement
// verbatim (ADR-004's version/capability model) rather than a redefinition,
// so this package never diverges from attachcontract's field names or JSON
// shape.
type Capabilities = attachcontract.CapabilityAdvertisement

// NewRequest builds a new presentation-plane request Envelope for the given
// op, JSON-marshaling payload into Envelope.Payload (payload may be nil, in
// which case Payload is left empty/omitted), generating a fresh
// crypto/rand-backed CorrelationID, and stamping SchemaVersion with this
// package's current SchemaVersion constant.
func NewRequest(op string, payload any) (Envelope, error) {
	var raw json.RawMessage
	if payload != nil {
		b, err := json.Marshal(payload)
		if err != nil {
			return Envelope{}, fmt.Errorf("presentationcontrol: marshal payload for op %q: %w", op, err)
		}
		raw = b
	}
	cid, err := newCorrelationID()
	if err != nil {
		return Envelope{}, fmt.Errorf("presentationcontrol: generate correlation id: %w", err)
	}
	return Envelope{
		SchemaVersion: SchemaVersion,
		Plane:         Plane,
		Op:            op,
		CorrelationID: cid,
		Payload:       raw,
	}, nil
}

// NewErrorResponse builds a presentation-plane error Envelope carrying the
// given correlationID (normally copied from the request this is responding
// to), category, and message. The returned Envelope has a nil Payload and a
// non-nil Error.
func NewErrorResponse(correlationID, category, message string) Envelope {
	return Envelope{
		SchemaVersion: SchemaVersion,
		Plane:         Plane,
		CorrelationID: correlationID,
		Error: &EnvelopeError{
			Category: category,
			Message:  message,
		},
	}
}

// newCorrelationID generates a fresh 128-bit crypto/rand-backed
// correlation identifier, hex-encoded. It is never derived from a counter,
// timestamp, or process ID, so correlation IDs remain unguessable and
// collision-free in practice across concurrent callers.
func newCorrelationID() (string, error) {
	var buf [16]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", fmt.Errorf("presentationcontrol: read random correlation id bytes: %w", err)
	}
	return hex.EncodeToString(buf[:]), nil
}
