package autogenskills

import (
	"archive/tar"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const DefaultCuratorBackupRetention = 5

// CuratorBackupManifest describes one restorable curator snapshot.
type CuratorBackupManifest struct {
	ID           string    `json:"id"`
	Reason       string    `json:"reason"`
	CreatedAt    time.Time `json:"created_at"`
	SizeBytes    int64     `json:"size_bytes"`
	FileCount    int       `json:"file_count"`
	SourceDigest string    `json:"source_digest"`
}

// CuratorBackupStore owns snapshots for one autogenerated-skill directory.
type CuratorBackupStore struct {
	AutogenDir string
	BackupDir  string
	Retention  int
	Now        func() time.Time
}

// CuratorRollbackResult identifies the restored and automatic safety snapshots.
type CuratorRollbackResult struct {
	Restored CuratorBackupManifest `json:"restored"`
	Safety   CuratorBackupManifest `json:"safety"`
}

// NewCuratorBackupStore creates a backup store. Empty backupDir selects
// <autogenDir>/.curator_backups; retention <= 0 selects five snapshots.
func NewCuratorBackupStore(autogenDir, backupDir string, retention int) (*CuratorBackupStore, error) {
	if autogenDir == "" {
		return nil, errors.New("curator backup: autogen directory is required")
	}
	root, err := filepath.Abs(autogenDir)
	if err != nil {
		return nil, err
	}
	if backupDir == "" {
		backupDir = filepath.Join(root, ".curator_backups")
	}
	backups, err := filepath.Abs(backupDir)
	if err != nil {
		return nil, err
	}
	if backups == root {
		return nil, errors.New("curator backup: backup directory cannot equal autogen directory")
	}
	if retention <= 0 {
		retention = DefaultCuratorBackupRetention
	}
	return &CuratorBackupStore{AutogenDir: root, BackupDir: backups, Retention: retention, Now: time.Now}, nil
}

// Snapshot writes a safe tar.gz and manifest, then applies retention.
func (s *CuratorBackupStore) Snapshot(reason string) (CuratorBackupManifest, error) {
	return s.snapshot(reason, nil)
}

func (s *CuratorBackupStore) snapshot(reason string, protect map[string]bool) (CuratorBackupManifest, error) {
	if err := os.MkdirAll(s.BackupDir, 0o700); err != nil {
		return CuratorBackupManifest{}, err
	}
	now := s.Now().UTC()
	base := now.Format("20060102T150405.000000000Z")
	id := base
	for n := 2; ; n++ {
		if _, err := os.Stat(filepath.Join(s.BackupDir, id)); errors.Is(err, os.ErrNotExist) {
			break
		}
		id = fmt.Sprintf("%s-%d", base, n)
	}
	tmp, err := os.MkdirTemp(s.BackupDir, ".snapshot-")
	if err != nil {
		return CuratorBackupManifest{}, err
	}
	defer os.RemoveAll(tmp)
	archivePath := filepath.Join(tmp, "skills.tar.gz")
	count, digest, err := s.writeArchive(archivePath)
	if err != nil {
		return CuratorBackupManifest{}, err
	}
	info, err := os.Stat(archivePath)
	if err != nil {
		return CuratorBackupManifest{}, err
	}
	m := CuratorBackupManifest{ID: id, Reason: reason, CreatedAt: now, SizeBytes: info.Size(), FileCount: count, SourceDigest: digest}
	raw, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return CuratorBackupManifest{}, err
	}
	if err := os.WriteFile(filepath.Join(tmp, "manifest.json"), append(raw, '\n'), 0o600); err != nil {
		return CuratorBackupManifest{}, err
	}
	if err := os.Rename(tmp, filepath.Join(s.BackupDir, id)); err != nil {
		return CuratorBackupManifest{}, err
	}
	if protect == nil {
		protect = make(map[string]bool)
	}
	protect[id] = true
	if err := s.prune(protect); err != nil {
		return m, err
	}
	return m, nil
}

func (s *CuratorBackupStore) writeArchive(path string) (int, string, error) {
	out, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return 0, "", err
	}
	gz := gzip.NewWriter(out)
	tw := tar.NewWriter(gz)
	hash := sha256.New()
	count := 0
	err = filepath.WalkDir(s.AutogenDir, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if samePath(path, s.BackupDir) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(s.AutogenDir, path)
		if err != nil || rel == "." {
			return err
		}
		if !safeArchiveName(filepath.ToSlash(rel)) {
			return fmt.Errorf("curator backup: unsafe source path %q", rel)
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 || (!info.Mode().IsRegular() && !info.IsDir()) {
			return fmt.Errorf("curator backup: unsupported file type %q", rel)
		}
		header, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		header.Name = filepath.ToSlash(rel)
		header.Uid, header.Gid, header.Uname, header.Gname = 0, 0, "", ""
		header.ModTime, header.AccessTime, header.ChangeTime = time.Time{}, time.Time{}, time.Time{}
		if err := tw.WriteHeader(header); err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		count++
		io.WriteString(hash, header.Name)
		hash.Write([]byte{0})
		file, err := os.Open(path)
		if err != nil {
			return err
		}
		_, copyErr := io.Copy(io.MultiWriter(tw, hash), file)
		closeErr := file.Close()
		if copyErr != nil {
			return copyErr
		}
		return closeErr
	})
	closeErr := tw.Close()
	if err == nil {
		err = closeErr
	}
	closeErr = gz.Close()
	if err == nil {
		err = closeErr
	}
	closeErr = out.Close()
	if err == nil {
		err = closeErr
	}
	if err != nil {
		return 0, "", err
	}
	return count, hex.EncodeToString(hash.Sum(nil)), nil
}

// List returns valid manifests, newest first.
func (s *CuratorBackupStore) List() ([]CuratorBackupManifest, error) {
	entries, err := os.ReadDir(s.BackupDir)
	if errors.Is(err, os.ErrNotExist) {
		return []CuratorBackupManifest{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := make([]CuratorBackupManifest, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() || !validBackupID(entry.Name()) {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(s.BackupDir, entry.Name(), "manifest.json"))
		if err != nil {
			continue
		}
		var m CuratorBackupManifest
		if json.Unmarshal(raw, &m) != nil || m.ID != entry.Name() {
			continue
		}
		out = append(out, m)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].CreatedAt.Equal(out[j].CreatedAt) {
			return out[i].ID > out[j].ID
		}
		return out[i].CreatedAt.After(out[j].CreatedAt)
	})
	return out, nil
}

func (s *CuratorBackupStore) prune(protect map[string]bool) error {
	items, err := s.List()
	if err != nil {
		return err
	}
	kept := 0
	for _, item := range items {
		if kept < s.Retention || protect[item.ID] {
			kept++
			continue
		}
		if err := os.RemoveAll(filepath.Join(s.BackupDir, item.ID)); err != nil {
			return err
		}
	}
	return nil
}

// Rollback restores a snapshot after taking a protected pre-rollback snapshot.
func (s *CuratorBackupStore) Rollback(id string) (CuratorRollbackResult, error) {
	if !validBackupID(id) {
		return CuratorRollbackResult{}, fmt.Errorf("curator backup: invalid snapshot id %q", id)
	}
	manifest, archive, err := s.loadSnapshot(id)
	if err != nil {
		return CuratorRollbackResult{}, err
	}
	stage, err := os.MkdirTemp(filepath.Dir(s.AutogenDir), ".curator-restore-")
	if err != nil {
		return CuratorRollbackResult{}, err
	}
	defer os.RemoveAll(stage)
	if err := extractSafeTar(archive, stage); err != nil {
		return CuratorRollbackResult{}, err
	}
	count, digest, err := digestRegularFiles(stage)
	if err != nil {
		return CuratorRollbackResult{}, err
	}
	if count != manifest.FileCount || digest != manifest.SourceDigest {
		return CuratorRollbackResult{}, errors.New("curator backup: snapshot content digest mismatch")
	}
	safety, err := s.snapshot("pre-rollback:"+id, map[string]bool{id: true})
	if err != nil {
		return CuratorRollbackResult{}, fmt.Errorf("curator backup: safety snapshot: %w", err)
	}
	old, err := os.MkdirTemp(filepath.Dir(s.AutogenDir), ".curator-old-")
	if err != nil {
		return CuratorRollbackResult{}, err
	}
	defer os.RemoveAll(old)
	current, err := os.ReadDir(s.AutogenDir)
	if err != nil {
		return CuratorRollbackResult{}, err
	}
	movedOld := []string{}
	for _, entry := range current {
		src := filepath.Join(s.AutogenDir, entry.Name())
		if samePath(src, s.BackupDir) {
			continue
		}
		if err := os.Rename(src, filepath.Join(old, entry.Name())); err != nil {
			restoreMoves(old, s.AutogenDir, movedOld)
			return CuratorRollbackResult{}, err
		}
		movedOld = append(movedOld, entry.Name())
	}
	staged, err := os.ReadDir(stage)
	if err == nil {
		for _, entry := range staged {
			if err = os.Rename(filepath.Join(stage, entry.Name()), filepath.Join(s.AutogenDir, entry.Name())); err != nil {
				break
			}
		}
	}
	if err != nil {
		for _, entry := range mustReadDir(s.AutogenDir) {
			if !samePath(filepath.Join(s.AutogenDir, entry.Name()), s.BackupDir) {
				_ = os.RemoveAll(filepath.Join(s.AutogenDir, entry.Name()))
			}
		}
		restoreMoves(old, s.AutogenDir, movedOld)
		return CuratorRollbackResult{}, fmt.Errorf("curator backup: restore: %w", err)
	}
	return CuratorRollbackResult{Restored: manifest, Safety: safety}, nil
}

func (s *CuratorBackupStore) loadSnapshot(id string) (CuratorBackupManifest, string, error) {
	dir := filepath.Join(s.BackupDir, id)
	raw, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return CuratorBackupManifest{}, "", err
	}
	var m CuratorBackupManifest
	if err := json.Unmarshal(raw, &m); err != nil || m.ID != id {
		return CuratorBackupManifest{}, "", fmt.Errorf("curator backup: invalid manifest for %q", id)
	}
	archive := filepath.Join(dir, "skills.tar.gz")
	info, err := os.Stat(archive)
	if err != nil || info.Size() != m.SizeBytes {
		return CuratorBackupManifest{}, "", fmt.Errorf("curator backup: snapshot size mismatch")
	}
	return m, archive, nil
}

func extractSafeTar(archive, root string) error {
	file, err := os.Open(archive)
	if err != nil {
		return err
	}
	defer file.Close()
	gz, err := gzip.NewReader(file)
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		header, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}
		if !safeArchiveName(header.Name) {
			return fmt.Errorf("curator backup: unsafe tar member %q", header.Name)
		}
		target := filepath.Join(root, filepath.FromSlash(header.Name))
		switch header.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, header.FileInfo().Mode().Perm()); err != nil {
				return err
			}
		case tar.TypeReg, tar.TypeRegA:
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			out, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, header.FileInfo().Mode().Perm())
			if err != nil {
				return err
			}
			_, copyErr := io.CopyN(out, tr, header.Size)
			closeErr := out.Close()
			if copyErr != nil {
				return copyErr
			}
			if closeErr != nil {
				return closeErr
			}
		default:
			return fmt.Errorf("curator backup: unsupported tar member %q", header.Name)
		}
	}
}

func digestRegularFiles(root string) (int, string, error) {
	hash := sha256.New()
	count := 0
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("curator backup: unsupported restored file %q", path)
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		count++
		io.WriteString(hash, filepath.ToSlash(rel))
		hash.Write([]byte{0})
		file, err := os.Open(path)
		if err != nil {
			return err
		}
		_, copyErr := io.Copy(hash, file)
		closeErr := file.Close()
		if copyErr != nil {
			return copyErr
		}
		return closeErr
	})
	return count, hex.EncodeToString(hash.Sum(nil)), err
}

func validBackupID(id string) bool {
	return id != "" && id == filepath.Base(id) && id != "." && id != ".." &&
		!strings.ContainsAny(id, `/\`) && !strings.HasPrefix(id, ".")
}

func safeArchiveName(name string) bool {
	if name == "" || strings.HasPrefix(name, "/") || strings.Contains(name, `\`) {
		return false
	}
	clean := filepath.ToSlash(filepath.Clean(filepath.FromSlash(name)))
	return clean == name && clean != "." && clean != ".." && !strings.HasPrefix(clean, "../")
}

func samePath(a, b string) bool {
	aa, _ := filepath.Abs(a)
	bb, _ := filepath.Abs(b)
	return filepath.Clean(aa) == filepath.Clean(bb)
}

func restoreMoves(from, to string, names []string) {
	for _, name := range names {
		_ = os.Rename(filepath.Join(from, name), filepath.Join(to, name))
	}
}

func mustReadDir(path string) []os.DirEntry {
	entries, _ := os.ReadDir(path)
	return entries
}
