// Package autogenskills implements the Hermes-style closed learning loop for
// the Swarm SDK skill system.
package autogenskills

import (
	"encoding/json"
	"fmt"
	"log"
	"maps"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// CuratorAction describes what a curator review recommends.
type CuratorAction string

const (
	// ActionNone means no action needed.
	ActionNone CuratorAction = "none"

	// ActionArchive means the skill is unused and should be archived.
	ActionArchive CuratorAction = "archive"

	// ActionMarkStale means the skill has crossed StaleAfterDays but not yet
	// ArchiveAfterDays — flag it as a candidate for archival without removing it.
	ActionMarkStale CuratorAction = "mark_stale"

	// ActionConsolidate means multiple similar skills could be merged.
	ActionConsolidate CuratorAction = "consolidate"

	// ActionPatch means the skill content may be outdated.
	ActionPatch CuratorAction = "patch"
)

// SkillState describes the lifecycle state of a skill.
type SkillState string

const (
	// SkillStateActive means the skill is in active use.
	SkillStateActive SkillState = "active"

	// SkillStateStale means the skill has gone unused past StaleAfterDays but
	// not yet ArchiveAfterDays. It is still rendered but flagged as a candidate
	// for archival (mirrors Hermes' intermediate "stale" state).
	SkillStateStale SkillState = "stale"

	// SkillStateArchived means the skill has been moved to the archive.
	SkillStateArchived SkillState = "archived"

	// SkillStatePinned means the skill is protected from auto-archive.
	SkillStatePinned SkillState = "pinned"

	// SkillStateConsolidated means the skill has been merged into another.
	SkillStateConsolidated SkillState = "consolidated"
)

// SkillMeta tracks per-skill metadata for curator decisions.
type SkillMeta struct {
	State         SkillState `json:"state"`
	LastUsedAt    time.Time  `json:"last_used_at"`
	CreatedAt     time.Time  `json:"created_at"`
	ArchivedAt    *time.Time `json:"archived_at,omitempty"`
	Pinned        bool       `json:"pinned"`
	Version       string     `json:"version"`
	AbsorbedInto  string     `json:"absorbed_into,omitempty"`
	ArchiveReason string     `json:"archive_reason,omitempty"`
}

// CuratorState is the persisted state of the curator.
type CuratorState struct {
	LastRunAt   time.Time            `json:"last_run_at"`
	Paused      bool                 `json:"paused"`
	SkillStates map[string]SkillMeta `json:"skill_states"`
}

// ReviewResult is the outcome of curating a single skill.
type ReviewResult struct {
	// SkillName is the skill under review.
	SkillName string

	// Action recommended by the curator.
	Action CuratorAction

	// Reason explains why the action was chosen.
	Reason string

	// Confidence is 0.0–1.0 (higher = more certain).
	Confidence float64

	// RelatedSkills lists overlapping skills for consolidation.
	RelatedSkills []string
}

// Curator performs background review of autogenerated skills.
//
// CONTRACT:
//   - Not a goroutine/scheduler — called explicitly during idle time.
//   - Never modifies skills directly; returns ReviewResult for caller to act on.
//   - Tracks skill lifecycle states and last_used_at per skill.
//   - Performs rule-based checks: archive, consolidation, patching, restoration.
//   - Persists state to .curator_state JSON file.
//   - Thread-safe: all methods protected by mutex.
//   - Construct via NewCurator; zero value is NOT usable.
type Curator struct {
	cfg       CuratorConfig
	factory   *SkillFactory
	state     *CuratorState
	statePath string
	mu        sync.Mutex
}

// NewCurator creates a curator from config and factory.
// statePath is where .curator_state JSON is persisted.
// If statePath is empty, defaults to <factory.AutogenDir>/.curator_state.
// Loads existing state from file if present; starts fresh if not.
func NewCurator(cfg CuratorConfig, factory *SkillFactory, statePath string) *Curator {
	c := &Curator{
		cfg:     cfg.WithDefaults(),
		factory: factory,
		state: &CuratorState{
			SkillStates: make(map[string]SkillMeta),
		},
		statePath: statePath,
	}

	// Derive default state path from factory config
	if c.statePath == "" && factory != nil {
		c.statePath = filepath.Join(factory.cfg.AutogenDir, ".curator_state")
	}

	// Load existing state (resilient: missing/corrupt = start fresh)
	if err := c.LoadState(); err != nil {
		log.Printf("curator: state load: %v; starting fresh", err)
	}

	return c
}

// ReviewAll examines all skills in the autogen directory.
// Returns a slice of ReviewResult, one per skill reviewed.
//
// CONTRACT:
//   - Non-destructive (read-only inspection).
//   - Errors are logged but do not stop review of other skills.
//   - Returns empty slice if autogen directory does not exist.
//   - Returns nil if curator is paused.
//   - Skips pinned skills from archive/consolidate recommendations.
//   - Checks: archive, consolidation candidates, patching candidates.
//
// reviewAllLocked examines all skills in the autogen directory.
// Caller must hold c.mu.
func (c *Curator) reviewAllLocked(autogenDir string) []ReviewResult {
	if c.state.Paused {
		return nil
	}

	var results []ReviewResult

	entries, err := os.ReadDir(autogenDir)
	if err != nil {
		return results // empty — dir may not exist yet
	}

	now := time.Now()

	// Phase 1: Per-skill checks (archive, patching).
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "archive" || strings.HasPrefix(entry.Name(), ".") {
			continue
		}

		name := entry.Name()
		skillDir := filepath.Join(autogenDir, name)
		skillPath := filepath.Join(skillDir, "SKILL.md")

		info, err := os.Stat(skillPath)
		if err != nil {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionNone,
				Reason:     "SKILL.md not found",
				Confidence: 1.0,
			})
			continue
		}

		// Parse skill frontmatter for tags and version.
		content, err := os.ReadFile(skillPath)
		if err != nil {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionNone,
				Reason:     "cannot read SKILL.md",
				Confidence: 1.0,
			})
			continue
		}
		fm, _, _ := parseSkillMarkdown(string(content))
		version := fm.Version
		if version == "" {
			version = "1.0.0"
		}

		// Use an ephemeral record for untracked skills. Review is a pure
		// preview; lifecycle seeding belongs to AutomaticTransitions.
		meta, exists := c.state.SkillStates[name]
		if !exists {
			meta = SkillMeta{
				State:      SkillStateActive,
				LastUsedAt: info.ModTime(), // Default: file mod time reflects last write
				CreatedAt:  info.ModTime(),
				Pinned:     false,
				Version:    version,
			}
		}

		// Skip pinned skills from archive/consolidate recommendations.
		if meta.Pinned {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionNone,
				Reason:     "skill is pinned",
				Confidence: 1.0,
			})
			continue
		}

		// Determine effective last_used_at (prefer state, fallback to mtime).
		lastUsed := meta.LastUsedAt
		if lastUsed.IsZero() {
			lastUsed = info.ModTime()
		}

		// Check archive.
		archiveAfter := time.Duration(c.cfg.ArchiveAfterDays) * 24 * time.Hour
		if now.Sub(lastUsed) > archiveAfter {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionArchive,
				Reason:     fmt.Sprintf("unused for %d days (threshold: %d)", int(now.Sub(lastUsed).Hours()/24), c.cfg.ArchiveAfterDays),
				Confidence: 0.9,
			})
			continue // archived skills don't need patch/consolidate checks
		}

		// Check stale: unused past StaleAfterDays but not yet ArchiveAfterDays.
		// Stale skills stay visible but are flagged as archival candidates
		// (mirrors Hermes' intermediate stale state). Skills still in their
		// active window fall through to patch/consolidate analysis below.
		staleAfter := time.Duration(c.cfg.StaleAfterDays) * 24 * time.Hour
		if staleAfter > 0 && now.Sub(lastUsed) > staleAfter {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionMarkStale,
				Reason:     fmt.Sprintf("unused for %d days (stale threshold: %d, archive at: %d)", int(now.Sub(lastUsed).Hours()/24), c.cfg.StaleAfterDays, c.cfg.ArchiveAfterDays),
				Confidence: 0.8,
			})
			continue
		}

		// Track whether we produced a non-none result for this skill.
		hasAction := false

		// Check patching: old skill still being used.
		patchAfter := time.Duration(c.cfg.PatchAfterDays) * 24 * time.Hour
		createdAt := meta.CreatedAt
		if createdAt.IsZero() {
			createdAt = info.ModTime()
		}
		if now.Sub(createdAt) > patchAfter && now.Sub(lastUsed) < archiveAfter {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionPatch,
				Reason:     fmt.Sprintf("created %d days ago, still actively used (last used %d days ago)", int(now.Sub(createdAt).Hours()/24), int(now.Sub(lastUsed).Hours()/24)),
				Confidence: 0.7,
			})
			hasAction = true
		}

		// If no action was recommended, emit ActionNone so callers always
		// get one result per skill.
		if !hasAction {
			results = append(results, ReviewResult{
				SkillName:  name,
				Action:     ActionNone,
				Reason:     "active within threshold",
				Confidence: 1.0,
			})
		}
	}

	return results
}

// ReviewAll examines all skills in the autogen directory.
// Returns a slice of ReviewResult, one per skill reviewed.
//
// CONTRACT:
//   - Non-destructive (read-only inspection) for archive/patch; consolidation
//     candidates are returned as recommendations.
//   - Errors are logged but do not stop review of other skills.
//   - Returns empty slice if autogen directory does not exist.
//   - Returns nil if curator is paused.
//   - Skips pinned skills from archive/consolidate recommendations.
//   - Checks: archive, consolidation candidates, patching candidates.
func (c *Curator) ReviewAll(autogenDir string) []ReviewResult {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.reviewAllLocked(autogenDir)
}

// Run performs the legacy analysis pass used by the curator CLI.
//
// CONTRACT:
//   - Pure analysis: does not reconcile, seed, prune, transition, archive, or
//     persist state.
//   - Patch-age recommendations are legacy analysis only.
//   - Returns nil, nil if curator is paused.
func (c *Curator) Run(autogenDir string) ([]ReviewResult, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.state.Paused {
		return nil, nil
	}
	return c.reviewAllLocked(autogenDir), nil
}

// SkillProtectionFunc reports whether an active skill is protected by an
// external scheduler or other owner. The SDK has no cron inventory API, so
// callers can provide known protected names without inventing scheduler state.
// A nil callback means no additional names are known; pinned skills are always
// protected.
type SkillProtectionFunc func(skillName string) bool

// AutomaticTransitions runs the deterministic Hermes lifecycle. It reconciles
// filesystem placement, seeds first-seen skills with a full grace period,
// transitions active and stale records in both directions, and atomically
// archives records beyond the archive threshold. It never emits patch-age
// recommendations and never invokes an LLM.
func (c *Curator) AutomaticTransitions(autogenDir string, protected SkillProtectionFunc) ([]ReviewResult, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.state.Paused {
		return nil, nil
	}

	now := time.Now()
	firstSeen := c.reconcileStateLocked(autogenDir, now)
	entries, err := os.ReadDir(autogenDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, c.saveStateLocked()
		}
		return nil, fmt.Errorf("curator: read autogen directory: %w", err)
	}

	staleAfter := time.Duration(c.cfg.StaleAfterDays) * 24 * time.Hour
	archiveAfter := time.Duration(c.cfg.ArchiveAfterDays) * 24 * time.Hour
	results := make([]ReviewResult, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "archive" || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		meta, ok := c.state.SkillStates[name]
		if !ok {
			continue
		}
		if firstSeen[name] {
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionNone,
				Reason: "first seen; grace period started", Confidence: 1,
			})
			continue
		}
		if meta.Pinned || (protected != nil && protected(name)) {
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionNone,
				Reason: "skill is protected", Confidence: 1,
			})
			continue
		}

		lastUsed := meta.LastUsedAt
		if lastUsed.IsZero() {
			// Old state formats may not have usage data. Treat discovery as the
			// beginning of grace rather than inferring disuse from file age.
			meta.LastUsedAt = now
			if meta.CreatedAt.IsZero() {
				meta.CreatedAt = now
			}
			if meta.State == SkillStateStale {
				meta.State = SkillStateActive
			}
			c.state.SkillStates[name] = meta
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionNone,
				Reason: "usage unknown; grace period started", Confidence: 1,
			})
			continue
		}

		age := now.Sub(lastUsed)
		switch {
		case archiveAfter > 0 && age >= archiveAfter:
			reason := fmt.Sprintf("unused for %d days (archive threshold: %d)", int(age.Hours()/24), c.cfg.ArchiveAfterDays)
			if _, err := c.archiveLocked(autogenDir, name, "", reason); err != nil {
				return results, err
			}
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionArchive,
				Reason: reason, Confidence: 1,
			})
		case staleAfter > 0 && age >= staleAfter:
			meta.State = SkillStateStale
			c.state.SkillStates[name] = meta
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionMarkStale,
				Reason:     fmt.Sprintf("unused for %d days (stale threshold: %d)", int(age.Hours()/24), c.cfg.StaleAfterDays),
				Confidence: 1,
			})
		default:
			if meta.State == SkillStateStale || meta.State == SkillStatePinned {
				meta.State = SkillStateActive
				c.state.SkillStates[name] = meta
			}
			results = append(results, ReviewResult{
				SkillName: name, Action: ActionNone,
				Reason: "active within threshold", Confidence: 1,
			})
		}
	}
	if err := c.saveStateLocked(); err != nil {
		return results, fmt.Errorf("curator: save state: %w", err)
	}
	return results, nil
}

// ReconcileAndSave makes active/archive filesystem placement authoritative and
// persists the result. Managers call this after an agent pass because the agent
// may have consolidated or restored skills through atomic skill-management
// tools.
func (c *Curator) ReconcileAndSave(autogenDir string) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.reconcileStateLocked(autogenDir, time.Now())
	return c.saveStateLocked()
}

// reconcileStateLocked makes the filesystem authoritative for active/archive
// placement while preserving usage and provenance fields. This repairs state
// drift after crashes, older SkillManage versions, or manual restores.
func (c *Curator) reconcileStateLocked(autogenDir string, now time.Time) map[string]bool {
	firstSeen := make(map[string]bool)
	if entries, err := os.ReadDir(autogenDir); err == nil {
		for _, entry := range entries {
			if !entry.IsDir() || entry.Name() == "archive" || strings.HasPrefix(entry.Name(), ".") {
				continue
			}
			name := entry.Name()
			meta, exists := c.state.SkillStates[name]
			if !exists {
				firstSeen[name] = true
				meta = SkillMeta{
					State:      SkillStateActive,
					CreatedAt:  now,
					LastUsedAt: now,
				}
			}
			if meta.CreatedAt.IsZero() {
				if info, statErr := entry.Info(); statErr == nil {
					meta.CreatedAt = info.ModTime()
				}
			}
			if meta.Pinned {
				meta.State = SkillStatePinned
			} else if meta.State == SkillStateArchived || meta.State == SkillStateConsolidated || meta.State == "" {
				meta.State = SkillStateActive
			}
			meta.ArchivedAt = nil
			meta.AbsorbedInto = ""
			meta.ArchiveReason = ""
			c.state.SkillStates[name] = meta
		}
	}

	archiveDir := filepath.Join(autogenDir, "archive")
	if entries, err := os.ReadDir(archiveDir); err == nil {
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			meta := c.state.SkillStates[entry.Name()]
			meta.State = SkillStateArchived
			if meta.ArchivedAt == nil {
				archivedAt := now
				if info, statErr := entry.Info(); statErr == nil {
					archivedAt = info.ModTime()
				}
				meta.ArchivedAt = &archivedAt
			}
			c.state.SkillStates[entry.Name()] = meta
		}
	}
	c.pruneDeletedLocked(autogenDir)
	return firstSeen
}

// pruneDeletedLocked removes state entries for skills that exist neither in
// the active autogen directory nor in its archive. Caller must hold c.mu.
func (c *Curator) pruneDeletedLocked(autogenDir string) {
	for name := range c.state.SkillStates {
		activePath := filepath.Join(autogenDir, name, "SKILL.md")
		archivePath := filepath.Join(autogenDir, "archive", name, "SKILL.md")
		if _, err := os.Stat(activePath); err == nil {
			continue
		}
		if _, err := os.Stat(archivePath); err == nil {
			continue
		}
		delete(c.state.SkillStates, name)
	}
}

// ConsolidateEnabled reports whether the LLM umbrella-consolidation pass is
// enabled in config. The rule-based curator no longer forms consolidation
// candidates programmatically — tag/token overlap collapses to noise at corpus
// scale (proven by dogfood: a shared-token rule linked ~130 skills to each of
// 239). Consolidation is now content-judged by the curator agent; this flag
// only tells that agent whether to run its umbrella pass.
func (c *Curator) ConsolidateEnabled() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.cfg.Consolidate
}

// Archive moves a skill to an archive subdirectory.
// CONTRACT:
//   - Creates archive/ under autogenDir if it doesn't exist.
//   - Updates the curator state to reflect the archived skill.
//   - Returns the new path or error.
//
// archiveLocked moves a skill to an archive subdirectory.
// Caller must hold c.mu.
func (c *Curator) archiveLocked(autogenDir, skillName, absorbedInto, reason string) (string, error) {
	if !isSafeSkillDirName(skillName) {
		return "", fmt.Errorf("curator: unsafe skill name %q", skillName)
	}
	if absorbedInto != "" && !isSafeSkillDirName(absorbedInto) {
		return "", fmt.Errorf("curator: unsafe absorption target %q", absorbedInto)
	}
	if meta, ok := c.state.SkillStates[skillName]; ok && meta.Pinned {
		return "", fmt.Errorf("curator: skill %q is pinned and cannot be archived", skillName)
	}

	src := filepath.Join(autogenDir, skillName)
	dst := filepath.Join(autogenDir, "archive", skillName)
	info, err := os.Lstat(src)
	if err != nil {
		return "", fmt.Errorf("curator: inspect %s: %w", skillName, err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return "", fmt.Errorf("curator: skill %q must be a real directory", skillName)
	}
	if _, err := os.Lstat(dst); err == nil {
		return "", fmt.Errorf("curator: archive destination already exists for %q", skillName)
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("curator: inspect archive destination for %s: %w", skillName, err)
	}

	if err := os.MkdirAll(filepath.Join(autogenDir, "archive"), 0755); err != nil {
		return "", fmt.Errorf("curator: mkdir archive: %w", err)
	}

	if err := os.Rename(src, dst); err != nil {
		return "", fmt.Errorf("curator: archive %s: %w", skillName, err)
	}

	previous, hadPrevious := c.state.SkillStates[skillName]
	meta := previous
	now := time.Now()
	if !hadPrevious {
		meta.CreatedAt = info.ModTime()
	}
	meta.State = SkillStateArchived
	meta.ArchivedAt = &now
	meta.AbsorbedInto = absorbedInto
	meta.ArchiveReason = reason
	c.state.SkillStates[skillName] = meta
	if err := c.saveStateLocked(); err != nil {
		_ = os.Rename(dst, src)
		if hadPrevious {
			c.state.SkillStates[skillName] = previous
		} else {
			delete(c.state.SkillStates, skillName)
		}
		return "", fmt.Errorf("curator: persist archive state for %s: %w", skillName, err)
	}

	return dst, nil
}

// Archive moves a skill to an archive subdirectory.
// CONTRACT:
//   - Creates archive/ under autogenDir if it doesn't exist.
//   - Updates the curator state to reflect the archived skill.
//   - Returns the new path or error.
func (c *Curator) Archive(autogenDir, skillName string) (string, error) {
	return c.ArchiveWithReason(autogenDir, skillName, "", "")
}

// ArchiveWithReason moves a skill into the recoverable archive and records
// whether its knowledge was absorbed into an umbrella or pruned for a stated
// reason.
func (c *Curator) ArchiveWithReason(autogenDir, skillName, absorbedInto, reason string) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.archiveLocked(autogenDir, skillName, absorbedInto, reason)
}

// Restore moves a skill from the archive back to the active directory.
// CONTRACT:
//   - Updates the curator state to reflect the restored skill.
//   - Returns the new path or error.
func (c *Curator) Restore(autogenDir, skillName string) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	src := filepath.Join(autogenDir, "archive", skillName)
	dst := filepath.Join(autogenDir, skillName)

	if err := os.Rename(src, dst); err != nil {
		return "", fmt.Errorf("curator: restore %s: %w", skillName, err)
	}

	// Update state.
	meta, ok := c.state.SkillStates[skillName]
	if ok {
		meta.State = SkillStateActive
		meta.ArchivedAt = nil
		meta.LastUsedAt = time.Now()
		meta.AbsorbedInto = ""
		meta.ArchiveReason = ""
	} else {
		meta = SkillMeta{
			State:      SkillStateActive,
			LastUsedAt: time.Now(),
			CreatedAt:  time.Now(),
		}
	}
	c.state.SkillStates[skillName] = meta

	if err := c.saveStateLocked(); err != nil {
		return "", fmt.Errorf("curator: persist restore state for %s: %w", skillName, err)
	}
	return dst, nil
}

// Pin marks a skill as pinned (survives auto-archive).
func (c *Curator) Pin(skillName string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	meta, ok := c.state.SkillStates[skillName]
	if !ok {
		meta = SkillMeta{
			State:      SkillStatePinned,
			LastUsedAt: time.Now(),
			CreatedAt:  time.Now(),
		}
	}
	meta.Pinned = true
	if meta.State != SkillStateArchived && meta.State != SkillStateConsolidated {
		meta.State = SkillStatePinned
	}
	c.state.SkillStates[skillName] = meta
	return c.saveStateLocked()
}

// Unpin removes the pinned state from a skill.
func (c *Curator) Unpin(skillName string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	meta, ok := c.state.SkillStates[skillName]
	if !ok {
		return fmt.Errorf("curator: skill %q not found in state", skillName)
	}
	meta.Pinned = false
	if meta.State == SkillStatePinned {
		meta.State = SkillStateActive
	}
	c.state.SkillStates[skillName] = meta
	return c.saveStateLocked()
}

// IsPinned reports whether a skill is protected from autonomous curator
// mutations.
func (c *Curator) IsPinned(skillName string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	meta, ok := c.state.SkillStates[skillName]
	return ok && meta.Pinned
}

// MarkUsed updates last_used_at for a skill.
// Called when a skill is invoked or viewed.
func (c *Curator) MarkUsed(skillName string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	meta, ok := c.state.SkillStates[skillName]
	if !ok {
		meta = SkillMeta{
			State:     SkillStateActive,
			CreatedAt: time.Now(),
		}
	}
	meta.LastUsedAt = time.Now()
	// A used skill is no longer stale — revive it to active (the archive ladder
	// resets on real usage, mirroring Hermes). Pinned/archived states are left
	// untouched.
	if meta.State == SkillStateStale {
		meta.State = SkillStateActive
	}
	c.state.SkillStates[skillName] = meta
	return c.saveStateLocked()
}

// NeedsReview returns true if there are skills old enough to review.
// Enhanced to check both archive and patch thresholds.
func (c *Curator) NeedsReview(autogenDir string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.state.Paused {
		return false
	}

	entries, err := os.ReadDir(autogenDir)
	if err != nil {
		return false
	}

	now := time.Now()
	archiveAfter := time.Duration(c.cfg.ArchiveAfterDays) * 24 * time.Hour
	patchAfter := time.Duration(c.cfg.PatchAfterDays) * 24 * time.Hour

	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "archive" || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		skillPath := filepath.Join(autogenDir, name, "SKILL.md")
		info, err := os.Stat(skillPath)
		if err != nil {
			continue
		}

		// Skip pinned.
		if meta, ok := c.state.SkillStates[name]; ok && meta.Pinned {
			continue
		}

		// Check archive age.
		lastUsed := info.ModTime()
		if meta, ok := c.state.SkillStates[name]; ok && !meta.LastUsedAt.IsZero() {
			lastUsed = meta.LastUsedAt
		}
		if now.Sub(lastUsed) > archiveAfter {
			return true
		}

		// Check patch age.
		createdAt := info.ModTime()
		if meta, ok := c.state.SkillStates[name]; ok && !meta.CreatedAt.IsZero() {
			createdAt = meta.CreatedAt
		}
		if now.Sub(createdAt) > patchAfter {
			return true
		}
	}

	return false
}

// SaveState persists .curator_state to disk.
// CONTRACT:
//   - Creates parent directories if needed.
//   - Returns error if statePath is empty or write fails.
//
// saveStateLocked persists state to disk. Caller must hold c.mu.
func (c *Curator) saveStateLocked() error {
	if c.statePath == "" {
		return fmt.Errorf("curator: no state path configured")
	}

	data, err := json.MarshalIndent(c.state, "", "  ")
	if err != nil {
		return fmt.Errorf("curator: marshal state: %w", err)
	}

	dir := filepath.Dir(c.statePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("curator: mkdir state dir: %w", err)
	}

	// Atomic write (temp + rename): the state file is shared by the TUI and
	// the daemon; a plain WriteFile interrupted mid-write leaves corrupt JSON
	// that silently resets the whole lifecycle history on next load.
	tmp, err := os.CreateTemp(dir, ".curator_state.tmp-*")
	if err != nil {
		return fmt.Errorf("curator: create temp state: %w", err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("curator: write temp state: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("curator: close temp state: %w", err)
	}
	if err := os.Chmod(tmpPath, 0644); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("curator: chmod temp state: %w", err)
	}
	if err := os.Rename(tmpPath, c.statePath); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("curator: rename state: %w", err)
	}

	return nil
}

// SaveState persists .curator_state to disk.
func (c *Curator) SaveState() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.saveStateLocked()
}

// LoadState loads .curator_state from disk.
// Missing file = start fresh (no error). Corrupt file = return error (caller
// should log warning and start fresh).
// CONTRACT:
//   - Initializes SkillStates map if nil after unmarshal.
//   - Does not acquire mutex (caller must hold lock or call before first use).
func (c *Curator) LoadState() error {
	if c.statePath == "" {
		return nil
	}

	data, err := os.ReadFile(c.statePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // fresh start
		}
		return fmt.Errorf("curator: read state: %w", err)
	}

	var state CuratorState
	if err := json.Unmarshal(data, &state); err != nil {
		return fmt.Errorf("curator: parse state: %w", err)
	}

	if state.SkillStates == nil {
		state.SkillStates = make(map[string]SkillMeta)
	}

	c.state = &state
	return nil
}

// GetState returns a copy of the current curator state.
func (c *Curator) GetState() *CuratorState {
	c.mu.Lock()
	defer c.mu.Unlock()

	stateCopy := *c.state
	stateCopy.SkillStates = make(map[string]SkillMeta, len(c.state.SkillStates))
	maps.Copy(stateCopy.SkillStates, c.state.SkillStates)
	return &stateCopy
}

// IsPaused returns whether the curator is paused.
func (c *Curator) IsPaused() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.state.Paused
}

// SetPaused pauses or resumes the curator.
// When paused, ReviewAll and NeedsReview return no results.
func (c *Curator) SetPaused(paused bool) {
	c.mu.Lock()
	c.state.Paused = paused
	c.mu.Unlock()
}

// SetLastRunAt updates the last run timestamp.
// CONTRACT: Thread-safe. Called after a curator run completes.
func (c *Curator) SetLastRunAt(t time.Time) {
	c.mu.Lock()
	c.state.LastRunAt = t
	c.mu.Unlock()
}

// ShouldRun is the single cadence gate for idle and headless callers. On a
// fresh installation it seeds LastRunAt and defers the first maintenance pass,
// preventing an immediate run before usage tracking has had a chance to work.
// It honors CuratorConfig.MinRunGap (default 24h).
// CONTRACT:
//   - Returns false if the curator is paused.
//   - Returns false and persists a cadence seed if LastRunAt is zero.
//   - Thread-safe.
func (c *Curator) ShouldRun() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.state.Paused {
		return false
	}
	if c.state.LastRunAt.IsZero() {
		c.state.LastRunAt = time.Now()
		if err := c.saveStateLocked(); err != nil {
			log.Printf("curator: persist initial cadence: %v", err)
		}
		return false
	}
	gap := 24 * time.Hour
	if d, err := time.ParseDuration(c.cfg.MinRunGap); err == nil && d > 0 {
		gap = d
	}
	return time.Since(c.state.LastRunAt) >= gap
}

// SetConsolidate enables or disables the consolidation pass for subsequent
// runs. Used by `swarm curator --consolidate` to force one consolidation run
// without editing config (mirrors `hermes curator run --consolidate`).
// CONTRACT: Thread-safe. Does not persist — config files stay authoritative
// across restarts.
func (c *Curator) SetConsolidate(enabled bool) {
	c.mu.Lock()
	c.cfg.Consolidate = enabled
	c.mu.Unlock()
}

// GetLastRunAt returns the last run timestamp (thread-safe).
func (c *Curator) GetLastRunAt() time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.state.LastRunAt
}
