// Package skilltools provides the Skill tool, which allows the LLM to invoke
// skills mid-conversation. This is the keystone feature that bridges the gap
// between Swarm's passive-context approach and Claude Code's active-tool-invocation
// architecture.
//
// CONTRACT:
//   - The Skill tool must be registered in the tool registry at session creation
//   - Skill resolution uses the skills.Registry for name-based lookup
//   - Skills with DisableModelInvocation=true cannot be invoked via this tool
//   - Argument substitution ({{arg}}) and variable substitution (${SWARM_*}) are
//     applied before returning content
//   - When context=="fork" and ForkExecutor is set, the skill content is sent
//     to an isolated sub-agent; otherwise execution falls back to inline.
package skilltools

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/Swarm-Code/mono/swarm-sdk/internal/observability"
	sdkerr "github.com/Swarm-Code/mono/swarm-sdk/internal/sdkerr"
	"github.com/Swarm-Code/mono/swarm-sdk/internal/skills"
	"github.com/Swarm-Code/mono/swarm-sdk/internal/tools"
)

// SkillToolConfig holds the configuration for creating a SkillTool.
type SkillToolConfig struct {
	// Registry is the skill registry for resolving skills by name. Required.
	Registry *skills.Registry

	// Logger for structured logging. Required.
	Logger observability.Logger

	// Tracer for distributed tracing. Required.
	Tracer observability.Tracer

	// SessionIDGetter returns the current session ID for variable substitution.
	// Optional; if nil, ${SWARM_SESSION_ID} is replaced with "".
	SessionIDGetter func() string

	// ForkExecutor runs a skill in an isolated sub-agent when context=="fork".
	// It receives the fully-substituted skill content as systemPrompt and
	// returns the sub-agent's response. Optional; when nil, fork-mode skills
	// fall back to inline execution with a warning prefix.
	//
	// Typical wire-up (from client or TUI):
	//
	//   ForkExecutor: func(ctx context.Context, systemPrompt string) (string, error) {
	//       reply, err := client.Chat(ctx, systemPrompt, client.WithFreshConversation())
	//       return reply, err
	//   }
	ForkExecutor func(ctx context.Context, systemPrompt string) (string, error)
}

// SkillTool allows the LLM to invoke skills mid-conversation.
// It implements the tools.Tool interface and is registered in the tool registry
// at session creation time.
//
// The LLM discovers available skills via a compact listing in the system prompt
// (generated by FormatSkillsWithinBudget), then explicitly calls the Skill tool
// to invoke one. The tool loads content, substitutes arguments and variables,
// and returns the content as a tool result.
//
// For skills with context: "fork", the tool calls ForkExecutor (if set) with
// the skill content as the system prompt for an isolated sub-agent.
type SkillTool struct {
	tools.BaseTool

	registry        *skills.Registry
	logger          observability.Logger
	tracer          observability.Tracer
	sessionIDGetter func() string
	forkExecutor    func(ctx context.Context, systemPrompt string) (string, error)
}

// NewSkillTool creates a new Skill tool.
func NewSkillTool(config SkillToolConfig) (*SkillTool, error) {
	if config.Registry == nil {
		return nil, sdkerr.Permanent("skill_tool.missing_registry", "registry is required")
	}
	if config.Logger == nil {
		return nil, sdkerr.Permanent("skill_tool.missing_logger", "logger is required")
	}
	if config.Tracer == nil {
		return nil, sdkerr.Permanent("skill_tool.missing_tracer", "tracer is required")
	}

	return &SkillTool{
		registry:        config.Registry,
		logger:          config.Logger,
		tracer:          config.Tracer,
		sessionIDGetter: config.SessionIDGetter,
		forkExecutor:    config.ForkExecutor,
	}, nil
}

// Name returns the tool name.
func (t *SkillTool) Name() string {
	return "Skill"
}

// Description returns the tool description shown to the LLM.
func (t *SkillTool) Description() string {
	return `Execute a skill within the main conversation.

When users ask you to perform tasks, check if any of the available skills match.
When a skill matches the user's request, this is a BLOCKING REQUIREMENT: invoke
the relevant Skill tool BEFORE generating any other response about the task.

Available skills are listed in system-reminder messages in the conversation.

Parameters:
  - skill: The name of the skill to invoke
  - args: Optional arguments to pass to the skill (space-separated)

The skill's instructions will be returned as the tool result. Follow them carefully.`
}

// Parameters returns the JSON schema for tool parameters.
func (t *SkillTool) Parameters() any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"skill": map[string]any{
				"type":        "string",
				"description": "The name of the skill to invoke. Available skills are listed in system-reminder messages.",
			},
			"args": map[string]any{
				"type":        "string",
				"description": "Optional arguments to pass to the skill. Space-separated values that replace {{arg}} placeholders in the skill content.",
			},
		},
		"required":             []string{"skill"},
		"additionalProperties": false,
	}
}

// IsIdempotent returns false — skill execution may have side effects (forked agents, shell commands).
func (t *SkillTool) IsIdempotent() bool {
	return false
}

// Validate checks that the skill parameter is provided.
func (t *SkillTool) Validate(params map[string]any) error {
	name, ok := params["skill"].(string)
	if !ok || name == "" {
		return sdkerr.Permanent("skill_tool.missing_skill", "skill parameter is required")
	}
	return nil
}

// SupportedContentTypes returns the content types this tool can produce.
func (t *SkillTool) SupportedContentTypes() []tools.ContentType {
	return []tools.ContentType{tools.ContentTypeText}
}

// Execute runs the Skill tool with the given parameters.
func (t *SkillTool) Execute(ctx context.Context, rawParams map[string]any) (*tools.ToolResult, error) {
	ctx, span := t.tracer.StartSpan(ctx, "skill_tool.execute")
	defer span.End()

	skillName, _ := rawParams["skill"].(string)
	args, _ := rawParams["args"].(string)

	if skillName == "" {
		return nil, sdkerr.Permanent("skill_tool.missing_skill", "skill parameter is required")
	}

	return t.Invoke(ctx, skillName, args)
}

// Invoke resolves and executes a skill by name.
func (t *SkillTool) Invoke(ctx context.Context, skillName, args string) (result *tools.ToolResult, err error) {
	startTime := time.Now()

	// Emit telemetry on return (measures full invocation duration including arg substitution)
	defer func() {
		durationMS := time.Since(startTime).Milliseconds()
		source := ""
		if skill, found := t.registry.Get(skillName); found {
			source = skill.LoadedFrom
		}
		skills.EmitSkillInvoked(skillName, source, durationMS, err)
	}()

	// 1. Resolve skill by name from registry
	skill, found := t.registry.Get(skillName)
	if !found {
		return nil, sdkerr.Permanent("skill_tool.not_found",
			fmt.Sprintf("skill %q not found in registry", skillName))
	}

	// 2. Check DisableModelInvocation
	if skill.Metadata.DisableModelInvocation {
		return nil, sdkerr.Permanent("skill_tool.disabled_invocation",
			fmt.Sprintf("skill %q cannot be used with the Skill tool due to disable-model-invocation", skillName))
	}

	// 3. Ensure content is loaded. Skills loaded from disk always have ContentLoaded=true
	// after the parser fix (LoadSkillWithValidation sets it). The fallback here
	// handles edge cases: skills registered programmatically without instructions,
	// or built-in skills whose embed set Instructions but not ContentLoaded.
	if !skill.ContentLoaded && skill.Instructions == "" {
		if skill.Path != "" && !strings.HasPrefix(skill.Path, "builtin:") {
			if reloaded, loadErr := skills.LoadSkill(skill.Path); loadErr == nil {
				// Mutate the registry's canonical pointer in place (skill is a *Skill).
				skill.Instructions = reloaded.Instructions
				skill.ContentLoaded = true
			}
		}
	}

	// 4. Get the skill content
	content := skill.Instructions
	if content == "" {
		return tools.NewToolResult(fmt.Sprintf("Skill %q has no instructions content.", skillName)), nil
	}

	// 5. Prepend skill directory context if available (mirrors Claude Code baseDir)
	if skill.Path != "" && !strings.HasPrefix(skill.Path, "builtin:") {
		content = fmt.Sprintf("Base directory for this skill: %s\n\n%s", skill.Path, content)
	}

	// 6. Substitute arguments ({{arg}} → value)
	if args != "" {
		content = skills.SubstituteArguments(content, args, skill.Metadata.Arguments)
	}

	// 7. Substitute variables (${SWARM_SKILL_DIR}, ${SWARM_SESSION_ID})
	sessionID := ""
	if t.sessionIDGetter != nil {
		sessionID = t.sessionIDGetter()
	}
	content = skills.SubstituteVariables(content, skill.Path, sessionID)

	t.logger.Info(ctx, "skill_tool.invoked",
		observability.F("skill", skillName),
		observability.F("context", skill.Metadata.Context),
		observability.F("has_args", args != ""),
	)

	// 8. Execute: fork or inline.
	if skill.Metadata.Context == "fork" {
		if t.forkExecutor != nil {
			// Run in isolated sub-agent with skill content as system prompt.
			output, forkErr := t.forkExecutor(ctx, content)
			if forkErr != nil {
				// Fork failed — fall back to inline with error note.
				t.logger.Warn(ctx, "skill_tool.fork_failed",
					observability.F("skill", skillName),
					observability.F("error", forkErr.Error()))
				return tools.NewToolResult(fmt.Sprintf(
					"[fork failed, running inline] %s", content)), nil
			}
			return tools.NewToolResult(output), nil
		}
		// ForkExecutor not wired — fall back to inline with a note.
		t.logger.Warn(ctx, "skill_tool.fork_no_executor",
			observability.F("skill", skillName))
		return tools.NewToolResult(fmt.Sprintf(
			"[fork mode not available, running inline] %s", content)), nil
	}

	// Inline mode: return content directly as tool result.
	return tools.NewToolResult(content), nil
}
