// Code generated by cmd/shimgen; DO NOT EDIT.

// Package codex is a compatibility shim.
//
// Deprecated: the implementation moved to internal/provider/codex. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package codex

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/provider/codex"
)

type Config = ipkg.Config
type Provider = ipkg.Provider

var New = ipkg.New
