// Code generated by cmd/shimgen; DO NOT EDIT.

// Package openai is a compatibility shim.
//
// Deprecated: the implementation moved to internal/provider/openai. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package openai

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/provider/openai"
)

type APIStreamError = ipkg.APIStreamError
type ChatCompletionChunk = ipkg.ChatCompletionChunk
type ChatCompletionRequest = ipkg.ChatCompletionRequest
type ChatCompletionResponse = ipkg.ChatCompletionResponse
type Choice = ipkg.Choice
type ChunkChoice = ipkg.ChunkChoice
type ChunkDelta = ipkg.ChunkDelta
type CodeExchange = ipkg.CodeExchange
type CompletionTokensDetails = ipkg.CompletionTokensDetails
type Config = ipkg.Config
type ConfigError = ipkg.ConfigError
type ContentPart = ipkg.ContentPart
type DeviceFlow = ipkg.DeviceFlow
type Factory = ipkg.Factory
type FactoryConfig = ipkg.FactoryConfig
type Function = ipkg.Function
type FunctionCall = ipkg.FunctionCall
type HTTPClientConfig = ipkg.HTTPClientConfig
type ImageURL = ipkg.ImageURL
type ModelCache = ipkg.ModelCache
type ModelInfo = ipkg.ModelInfo
type ModelListResponse = ipkg.ModelListResponse
type OAuthConfig = ipkg.OAuthConfig
type OAuthToken = ipkg.OAuthToken
type OpenAIMessage = ipkg.OpenAIMessage
type PromptTokensDetails = ipkg.PromptTokensDetails
type Provider = ipkg.Provider
type ReasoningOptions = ipkg.ReasoningOptions
type ResponseFormat = ipkg.ResponseFormat
type StreamOptions = ipkg.StreamOptions
type TextFormat = ipkg.TextFormat
type TextOptions = ipkg.TextOptions
type Tool = ipkg.Tool
type ToolCall = ipkg.ToolCall
type ToolFormat = ipkg.ToolFormat
type Usage = ipkg.Usage

var ClearOAuthToken = ipkg.ClearOAuthToken
var ExchangeCodeForToken = ipkg.ExchangeCodeForToken
var ExtractAccountIDFromIDToken = ipkg.ExtractAccountIDFromIDToken
var FetchAndSaveModels = ipkg.FetchAndSaveModels
var GetStoredOAuthToken = ipkg.GetStoredOAuthToken
var HasModelRequestScope = ipkg.HasModelRequestScope
var IsMessageValid = ipkg.IsMessageValid
var IsTokenExpired = ipkg.IsTokenExpired
var LoadOAuthConfig = ipkg.LoadOAuthConfig
var MapFinishReason = ipkg.MapFinishReason
var New = ipkg.New
var NewFactory = ipkg.NewFactory
var NewFromEnv = ipkg.NewFromEnv
var NewHTTPClient = ipkg.NewHTTPClient
var NewModelCache = ipkg.NewModelCache
var OAuthDeviceVerificationURL = ipkg.OAuthDeviceVerificationURL
var PollForAuthorizationCode = ipkg.PollForAuthorizationCode
var PollForAuthorizationCodeWithCallback = ipkg.PollForAuthorizationCodeWithCallback
var ProviderFactory = ipkg.ProviderFactory
var RefreshAccessToken = ipkg.RefreshAccessToken
var RefreshAndStoreToken = ipkg.RefreshAndStoreToken
var Register = ipkg.Register
var SanitizeMessage = ipkg.SanitizeMessage
var SanitizeMessages = ipkg.SanitizeMessages
var SaveOAuthConfig = ipkg.SaveOAuthConfig
var StartDeviceFlow = ipkg.StartDeviceFlow
var StoreOAuthToken = ipkg.StoreOAuthToken
var TranslateMessage = ipkg.TranslateMessage
var TranslateRequest = ipkg.TranslateRequest
var TranslateResponse = ipkg.TranslateResponse
var TranslateTool = ipkg.TranslateTool
var TranslateToolCall = ipkg.TranslateToolCall
var TranslateToolCallFromOpenAI = ipkg.TranslateToolCallFromOpenAI
