// Code generated by cmd/shimgen; DO NOT EDIT.

// Package analytics is a compatibility shim.
//
// Deprecated: the implementation moved to internal/analytics. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package analytics

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/analytics"
)

type ArtifactBatchRequest = ipkg.ArtifactBatchRequest
type ArtifactEnvelope = ipkg.ArtifactEnvelope
type ArtifactSpool = ipkg.ArtifactSpool
type BatchRequest = ipkg.BatchRequest
type BatchResponse = ipkg.BatchResponse
type Client = ipkg.Client
type Config = ipkg.Config
type Dispatcher = ipkg.Dispatcher
type DispatcherStats = ipkg.DispatcherStats
type EventEnvelope = ipkg.EventEnvelope
type NoopTracker = ipkg.NoopTracker
type QueueStats = ipkg.QueueStats
type RedactionResult = ipkg.RedactionResult
type Redactor = ipkg.Redactor
type Spool = ipkg.Spool
type Tracker = ipkg.Tracker

const DefaultAuthToken = ipkg.DefaultAuthToken
const DefaultCollectorURL = ipkg.DefaultCollectorURL
const DefaultSource = ipkg.DefaultSource
const SchemaVersion = ipkg.SchemaVersion

var ConfigFromEnv = ipkg.ConfigFromEnv
var DeviceIDHash = ipkg.DeviceIDHash
var HashMachineID = ipkg.HashMachineID
var HashValue = ipkg.HashValue
var MachineIDHash = ipkg.MachineIDHash
var NewArtifactSpool = ipkg.NewArtifactSpool
var NewClient = ipkg.NewClient
var NewDispatcher = ipkg.NewDispatcher
var NewEventID = ipkg.NewEventID
var NewManualDispatcher = ipkg.NewManualDispatcher
var NewRedactor = ipkg.NewRedactor
var NewSpool = ipkg.NewSpool
var WorkspaceHash = ipkg.WorkspaceHash
var WorkspaceLabel = ipkg.WorkspaceLabel
