/**
 * Render Pi's structured SkillManage results as the exact prose Swarm's
 * SkillManageTool returns (mono/swarm-sdk internal/skills/autogenskills/
 * skillmanage.go). Swarm reports validation problems as ordinary, non-error
 * tool results ("Patch failed: …"); only unexpected failures propagate as
 * errors. `renderSkillManageError` mirrors that split.
 */
export const VIEW_INSTRUCTION_PAGE_LIMIT = 80_000;

const q = (value: unknown) => JSON.stringify(String(value ?? ""));
const short = (digest: string) => (digest.length <= 12 ? digest : digest.slice(0, 12));
const previousVersion = (version: string) => {
  const parts = version.split(".");
  return parts.length === 3 && /^\d+$/.test(parts[2]) && Number(parts[2]) > 0 ? `${parts[0]}.${parts[1]}.${Number(parts[2]) - 1}` : version;
};

export function renderSkillManageResult(action: string, params: any, result: any): string {
  switch (action) {
    case "list": {
      const skills: any[] = result?.skills ?? [];
      if (skills.length === 0) return "No autogenerated skills exist yet. Use 'create' to make your first skill.";
      return `Found ${skills.length} autogenerated skill(s):\n\n${skills.map(s => `- **${s.name}** (v${s.version || "?.?.?"}): ${s.description}\n`).join("")}`;
    }
    case "review":
      return `Skill review completed without mutation: ${String(result?.reason ?? params?.review_reason ?? "").trim()}`;
    // factory.go reports Path = <package>/SKILL.md for create and patch.
    case "create":
      return `Created skill ${q(result?.skill?.name)} at ${result?.skill?.path}/SKILL.md\nRevision: ${result?.revision}`;
    case "patch":
      return `Patched skill ${q(result?.skill?.name)} (v${previousVersion(String(result?.version ?? result?.skill?.version ?? ""))} → v${result?.version ?? result?.skill?.version}) at ${result?.skill?.path}/SKILL.md\nRevision: ${result?.revision}`;
    case "write_file":
      return `Wrote support file for ${q(params?.name)} at ${result?.path}\nRevision: ${result?.revision}`;
    case "absorb_files": {
      const files: string[] = result?.files ?? [];
      let b = `Absorbed ${files.length} support file(s) from ${q(params?.from_skill)} into ${q(params?.name)}, byte-for-byte:\n`;
      let copied = 0;
      for (const file of files) {
        const skippedReason = result?.skipped?.[file];
        if (skippedReason) { b += `  = ${file} (${result?.sizes?.[file] ?? 0} bytes, ${skippedReason})\n`; continue; }
        copied++;
        b += `  + ${file} (${result?.sizes?.[file] ?? 0} bytes, sha256:${short(String(result?.digests?.[file] ?? ""))})\n`;
      }
      if (result?.revision) b += `Revision: ${result.revision}\n`;
      if (copied > 0) b += "Every copy was verified by re-hashing the destination.\n";
      return b + "Now update the destination instructions to reference the new paths.";
    }
    case "read_file": {
      const rel = String(params?.file_path ?? "").replace(/\\/g, "/").replace(/\/+/g, "/").replace(/^\.\//, "");
      return `═══ SUPPORT FILE: ${params?.name}/${rel} ═══\nRevision: ${result?.revision}\n${result?.content ?? ""}`;
    }
    case "view": {
      const s = result?.skill ?? {};
      const full = String(result?.instructions_total ?? s.instructions ?? "");
      const totalChars = typeof result?.total_chars === "number" ? result.total_chars : [...full].length;
      const hasOffset = params?.offset !== undefined, hasLimit = params?.limit !== undefined;
      const paged = hasOffset || hasLimit || totalChars > VIEW_INSTRUCTION_PAGE_LIMIT;
      let offset = hasOffset ? Number(params.offset) : 0;
      if (offset > totalChars) offset = totalChars;
      let limit = hasLimit ? Number(params.limit) : VIEW_INSTRUCTION_PAGE_LIMIT;
      if (!hasLimit || limit > VIEW_INSTRUCTION_PAGE_LIMIT) limit = VIEW_INSTRUCTION_PAGE_LIMIT;
      const end = Math.min(offset + limit, totalChars);
      let b = `═══ SKILL: ${s.name} — Follow these instructions ═══\n# ${s.name}\nVersion: ${s.version}\nDescription: ${s.description}\n`;
      if (Array.isArray(s.tags) && s.tags.length > 0) b += `Tags: ${s.tags.join(", ")}\n`;
      b += `Source: ${result?.source ?? "autogen"}\nRevision: ${result?.revision}\n`;
      if (paged) b += `expected_revision: ${result?.revision}\nInstructions range: [${offset},${end}) of ${totalChars} Unicode characters\n`;
      b += `\n${s.instructions ?? ""}`;
      const support: string[] = result?.support_files ?? [];
      if (support.length > 0) b += `\n\nSupport files (load only when needed with SkillManage action=read_file):\n${support.map(p => `- ${p}\n`).join("")}`;
      return b + `\n═══ If anything above is outdated or incorrect, call SkillManage(action: "patch", name: "${s.name}", ...) immediately. ═══\n`;
    }
    case "history": {
      const revisions: any[] = (result?.revisions ?? []).map((r: any) => ({
        id: r.id, ...(r.parent ? { parent: r.parent } : {}), action: r.action, ...(r.revert_of ? { revert_of: r.revert_of } : {}),
        created_at: r.createdAt ?? r.created_at, placement: r.placement ?? "active",
      }));
      const limit = params?.limit;
      return JSON.stringify(typeof limit === "number" && limit < revisions.length ? revisions.slice(0, limit) : revisions, null, 2);
    }
    case "undo":
      return `Restored skill ${q(params?.name)}\nRevision: ${result?.revision}`;
    case "archive":
      return `Archived skill ${q(params?.name)} to ${result?.path}\nRevision: ${result?.revision}`;
    default:
      return typeof result === "string" ? result : JSON.stringify(result);
  }
}

export const SKILL_MANAGE_ACTIONS = ["create", "patch", "write_file", "absorb_files", "read_file", "review", "view", "history", "undo", "list", "archive"];
export const unknownActionText = (action: unknown) =>
  `Unknown action ${q(action)}. Use create, patch, write_file, absorb_files, read_file, review, view, history, undo, list, or archive.`;

/** Swarm's non-error validation prose for a failed action; undefined keeps Pi's error path. */
export function renderSkillManageError(action: string, params: any, message: string): string | undefined {
  const name = params?.name;
  switch (action) {
    case "create": return `Skill creation failed: ${message}`;
    case "patch": return !name ? "patch requires a 'name' parameter" : `Patch failed: ${message}`;
    case "write_file":
      if (!name || !params?.file_path) return "write_file requires 'name' and 'file_path'";
      if (!params?.file_content) return "write_file requires non-empty 'file_content'";
      return `write_file failed: ${message}`;
    case "absorb_files": return !name || !params?.from_skill ? "absorb_files requires 'from_skill' (source) and 'name' (destination umbrella)" : `absorb_files failed: ${message}`;
    case "read_file": return !name || !params?.file_path ? "read_file requires 'name' and 'file_path'" : `read_file failed: ${message}`;
    case "review": return "review requires a non-empty 'review_reason'";
    case "view": return !name ? "view requires a 'name' parameter" : `Failed to view skill: ${message}`;
    case "history": return !name ? "history requires a 'name' parameter" : `History failed: ${message}`;
    case "undo": return !name ? "undo requires a 'name' parameter" : `Undo failed: ${message}`;
    case "archive":
      if (!name) return "archive requires a 'name' parameter";
      if (!String(params?.absorbed_into ?? "").trim() && !String(params?.pruning_reason ?? "").trim()) return "archive requires 'absorbed_into' after consolidation or 'pruning_reason' for true pruning";
      if (params?.absorbed_into === name) return "archive absorbed_into must name a different umbrella skill";
      return `Archive failed: ${message}`;
    default: return undefined;
  }
}
