import { describe, expect, it, vi } from "vitest";
import { AutoSkillManager, CuratorOrchestrator, registerAutoSkills } from "../src/index.js";
import { registerAutoSkillsExtension } from "../../.pi/extensions/autogenskills.ts";
import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const instructions = "A reusable production procedure. ".repeat(8);
const manager = (extra = {}) => new AutoSkillManager({ dir: mkdtempSync(join(tmpdir(), "autogen-")), mode: "auto", ...extra });
const digest = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const revisionId = (skill: string, parent: string, action: string, files: Record<string, string>) =>
  digest(JSON.stringify({ format: 1, skill, parent, action, files }));

describe("autogenerated skills", () => {
  it("defaults to safe never mode and validates exact modes", () => {
    expect(new AutoSkillManager({ dir: "/tmp/x" }).config.mode).toBe("never");
    expect(new AutoSkillManager({ mode: "auto" }).config.toolCallBudget).toBe(5);
    expect(new AutoSkillManager({ mode: "auto" }).config.workingBudget).toBe(90);
    expect(() => new AutoSkillManager({ mode: "invalid" as any })).toThrow(/invalid autogen mode/);
  });
  it("tracks metrics, revisions, review hooks, and pinning", () => {
    const events: any[] = [], m = manager({ reviewHook: e => events.push(e) });
    const created: any = m.execute({ action: "create", name: "build-check", description: "Build checks", instructions });
    expect(created.revision).toMatch(/^[a-f0-9]{64}$/);
    expect(m.execute({ action: "metrics" }).metrics.mutations).toBe(1);
    expect(m.execute({ action: "pin", name: "build-check" }).state).toBe("pinned");
    expect(() => m.execute({ action: "archive", name: "build-check" })).toThrow(/pinned/);
    expect(events.map(e => e.action)).toEqual(["create", "pin"]);
  });
  it("rejects stale mutations until a review and supports expected revisions", () => {
    const m = manager({ toolCallBudget: 1 });
    m.observeTool(true, "TaskManage", { status: "in_progress", active: true });
    m.observeTool(true, "bash");
    expect(() => m.execute({ action: "create", name: "too-late", description: "x", instructions })).toThrow(/budget/);
  });
  it("rehydrates the complete budget state from Pi session entries", () => {
    const entries: any[] = [];
    const first = new AutoSkillManager({ dir: mkdtempSync(join(tmpdir(), "autogen-")), mode: "auto" }, (entry: any) => entries.push(entry));
    first.observeTool(true, "bash", { command: "node build" });
    first.observeTool(false, "write", { path: "x" });
    const before = first.snapshot();
    const restored = manager();
    restored.rehydrate(entries.map(entry => ({
      type: "custom",
      customType: entry.type,
      data: entry.data,
    })));
    expect(restored.snapshot()).toMatchObject({
      toolCalls: before.toolCalls,
      budgetCalls: before.budgetCalls,
      errors: before.errors,
      skilled: before.skilled,
      reviewRequired: before.reviewRequired,
    });
    restored.rehydrate([]);
    expect(restored.snapshot()).toEqual(expect.objectContaining({
      toolCalls: 0,
      budgetCalls: 0,
      errors: 0,
      reviewRequired: false,
    }));
  });
  it("hard-blocks onboarding calls and escalates working-tier nudges", () => {
    const onboarding = manager({ toolCallBudget: 1 });
    onboarding.observeTool(true, "TaskManage", { status: "in_progress", active: true });
    onboarding.observeTool(true, "bash");
    expect(onboarding.gateTool("write", { path: "x" })).toMatchObject({ block: true });

    const working = manager({ toolCallBudget: 1, workingBudget: 2, maxNudgeIgnores: 2, nudgeInterval: 1, toolCallThreshold: 1 });
    working.observeTool(true, "Skill", { skill: "external-skill" });
    working.observeTool(true, "write");
    working.observeTool(true, "write");
    expect(working.observeTurn()).toBeUndefined();
    expect(working.observeTurn()).toContain("Review reusable learning");
    expect(working.observeTurn()).toContain("review required");
    expect(working.gateTool("write")).toMatchObject({ block: true, reason: expect.stringContaining("review required") });
  });

  it("registers no hooks or tools in never mode", () => {
    const events: string[] = [], tools: string[] = [];
    registerAutoSkills({
      appendEntry() {},
      on(event: string) { events.push(event); },
      registerTool(tool: any) { tools.push(tool.name); },
    }, { mode: "never", dir: mkdtempSync(join(tmpdir(), "autogen-")) });
    expect(events).toEqual([]);
    expect(tools).toEqual([]);
  });

  it("appends lifecycle nudges to tool content for model visibility", async () => {
    const handlers = new Map<string, Array<(event: any, ctx: any) => unknown>>();
    registerAutoSkills({
      appendEntry() {},
      on(event: string, handler: (event: any, ctx: any) => unknown) {
        handlers.set(event, [...(handlers.get(event) ?? []), handler]);
      },
      registerTool() {},
    }, {
      mode: "auto",
      dir: mkdtempSync(join(tmpdir(), "autogen-")),
      nudgeInterval: 1,
      toolCallThreshold: 1,
    });
    const resultHook = handlers.get("tool_result")![0];
    await resultHook({ toolName: "read", content: [{ type: "text", text: "first" }] }, {});
    const result: any = await resultHook({ toolName: "read", content: [{ type: "text", text: "second" }] }, {});
    expect(result.content[0].text).toBe("second");
    expect(result.content.at(-1).text).toContain("Review reusable learning");
  });

  it("charges every Bash command at tool_call time, including read-only commands", () => {
    const m = manager({ toolCallBudget: 10 });
    m.observeTool(true, "TaskManage", { operations: [{ status: "in_progress", active: true }] });
    m.observeToolAttempt("bash", { command: "pwd" }, "bash-1");
    m.observeToolAttempt("bash", { command: "ls" }, "bash-2");
    m.observeToolAttempt("bash", { command: "rg pattern file" }, "bash-3");
    expect(m.budgetStatus().used).toBe(3);
    // A duplicate terminal notification is a result observation, not another
    // budget attempt, and a failed command remains charged.
    m.observeTool(false, "bash", { command: "false" }, "bash-3");
    expect(m.budgetStatus().used).toBe(3);
  });

  it("separates one turn from multiple tool results", () => {
    const m = manager({ nudgeInterval: 1, toolCallThreshold: 1 });
    m.observeTurn();
    m.observeTool(true, "bash", { command: "pwd" }, "call-1");
    m.observeTool(true, "bash", { command: "ls" }, "call-2");
    m.observeTurn();
    expect(m.metrics().turns).toBe(2);
    expect(m.metrics().toolCalls).toBe(2);
  });

  it("renders a theme-colored progress widget matching the TUI conventions", () => {
    const m = manager({ toolCallBudget: 4 });
    m.observeTool(true, "TaskManage", { operations: [{ status: "in_progress", active: true }] });
    m.observeToolAttempt("bash", {}, "budget-call");
    const calls: string[] = [];
    const widget: any = m.budgetWidget({}, { fg: (color: string, text: string) => { calls.push(color); return `<${color}>${text}</${color}>`; }, dim: (text: string) => `<dim>${text}</dim>` });
    const line = widget.render(80)[0];
    expect(line).toContain("Autogen");
    expect(line).toContain("1/4");
    expect(line).toContain("<accent>█");
    expect(line).toContain("<dim>░");
    expect(calls).toContain("accent");
    expect(calls).toContain("warning");
  });

  it("emits an upstream-style skill-review nudge from post-tool activity", () => {
    const m = manager({ nudgeInterval: 2 });
    m.observeTool(true, "TaskManage", { operations: [{ status: "in_progress", active: true }] });
    m.observeTool(true, "custom_tool", {}, "nudge-1");
    m.observeTool(true, "custom_tool", {}, "nudge-2");
    const nudge = m.observeTool(true, "custom_tool", {}, "nudge-3");
    expect(nudge).toContain("[SKILL REVIEW]");
    expect(nudge).toContain("patch a loaded skill");
    expect(nudge).toContain("no-mutation review");
  });

  it("uses Pi tool_result input to activate focused-task budget accounting", async () => {
    const handlers = new Map<string, Array<(event: any, ctx: any) => unknown>>();
    const m = registerAutoSkills({
      appendEntry() {},
      on(event: string, handler: (event: any, ctx: any) => unknown) {
        handlers.set(event, [...(handlers.get(event) ?? []), handler]);
      },
      registerTool() {},
    }, {
      mode: "auto",
      dir: mkdtempSync(join(tmpdir(), "autogen-")),
    });
    const resultHook = handlers.get("tool_result")![0];
    await resultHook({
      toolName: "TaskManage",
      input: { operations: [{ key: "focus", op: "update", status: "in_progress", active: true }] },
      content: [],
      isError: false,
    }, {});
    await resultHook({ toolName: "write", input: { path: "x" }, content: [], isError: true }, {});
    expect(m.budgetStatus().used).toBe(1);
    expect(m.metrics().errors).toBe(1);
  });

  it("absorbs support files byte-for-byte and guards archival provenance", () => {
    const m = manager();
    const source: any = m.execute({ action: "create", name: "source-skill", description: "Source", instructions });
    const target: any = m.execute({ action: "create", name: "target-skill", description: "Target", instructions });
    const written: any = m.execute({ action: "write_file", name: "source-skill", file_path: "assets/data.bin", file_content: "\u0000binary\u00ff", expected_revision: source.revision });
    expect(() => m.execute({ action: "archive", name: "source-skill", expected_revision: written.revision, absorbed_into: "target-skill" })).toThrow(/absorb_files/);
    const absorbed: any = m.execute({ action: "absorb_files", name: "target-skill", from_skill: "source-skill", expected_revision: target.revision });
    expect(absorbed.files).toEqual(["assets/data.bin"]);
    const archived: any = m.execute({ action: "archive", name: "source-skill", expected_revision: written.revision, absorbed_into: "target-skill" });
    expect(archived.absorbed_into).toBe("target-skill");
  });

  it("undo requires the exact head and removes files absent from the target revision", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "undo-skill", description: "Undo", instructions });
    const first: any = m.execute({ action: "write_file", name: "undo-skill", file_path: "references/one.txt", file_content: "one", expected_revision: created.revision });
    const second: any = m.execute({ action: "write_file", name: "undo-skill", file_path: "references/two.txt", file_content: "two", expected_revision: first.revision });
    expect(() => m.execute({ action: "undo", name: "undo-skill", revision: created.revision, expected_revision: "1.0.0" })).toThrow(/revision conflict for skill "undo-skill": expected 1\.0\.0, current [a-f0-9]{64}; view the skill and retry/);
    m.execute({ action: "undo", name: "undo-skill", revision: created.revision, expected_revision: second.revision });
    expect(existsSync(join(m.config.dir, "undo-skill", "references", "one.txt"))).toBe(false);
    expect(existsSync(join(m.config.dir, "undo-skill", "references", "two.txt"))).toBe(false);
  });

  it("rolls an undo swap back when revert revision publication fails", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "undo-rollback", description: "Undo", instructions });
    const current: any = m.execute({
      action: "write_file",
      name: "undo-rollback",
      file_path: "references/current.txt",
      file_content: "current",
      expected_revision: created.revision,
    });
    const createdManifest = JSON.parse(readFileSync(join(
      m.config.dir, ".history", "revisions", "undo-rollback", `${created.revision}.json`,
    ), "utf8"));
    const future = revisionId("undo-rollback", current.revision, "undo", createdManifest.files);
    writeFileSync(join(m.config.dir, ".history", "revisions", "undo-rollback", `${future}.json`), "{}");

    expect(() => m.execute({
      action: "undo",
      name: "undo-rollback",
      revision: created.revision,
      expected_revision: current.revision,
    })).toThrow(/untrusted revision manifest/);
    expect(readFileSync(join(m.config.dir, "undo-rollback", "references", "current.txt"), "utf8")).toBe("current");
    expect(readFileSync(join(m.config.dir, ".history", "heads", "undo-rollback"), "utf8").trim()).toBe(current.revision);
  });

  it("curates stale skills on cadence while preserving pinned skills", () => {
    const m = manager({ staleAfterDays: 30, archiveAfterDays: 90 });
    m.execute({ action: "create", name: "old-skill", description: "Old", instructions });
    m.execute({ action: "create", name: "pinned-skill", description: "Pinned", instructions });
    m.execute({ action: "pin", name: "pinned-skill" });
    const state = m.snapshot();
    const old = new Date("2025-01-01T00:00:00.000Z").toISOString();
    state.skills["old-skill"].lastUsed = old;
    state.skills["pinned-skill"].lastUsed = old;
    m.restore(state);
    writeFileSync(join(m.config.dir, ".history", "curator-state.json"), `${JSON.stringify({
      skills: state.skills,
      curatorLastRun: state.curatorLastRun,
      curatorLastReport: state.curatorLastReport,
    }, null, 2)}\n`);
    expect(m.curate(Date.parse("2025-04-14T00:00:00.000Z")).ran).toBe(false);
    const result = m.curate(Date.parse("2025-04-15T00:00:00.000Z"));
    expect(result.archived).toEqual(["old-skill"]);
    expect(m.snapshot().skills["pinned-skill"].curatorState).toBe("pinned");
    expect(m.curate(Date.parse("2025-04-15T01:00:00.000Z")).ran).toBe(false);
  });

  it("rechecks persisted pin state before stale archival", () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-pin-race-"));
    const owner = new AutoSkillManager({ dir, mode: "manual" });
    owner.execute({ action: "create", name: "race-pinned", description: "Pinned", instructions });
    const statePath = join(dir, ".history", "curator-state.json");
    const disk = JSON.parse(readFileSync(statePath, "utf8"));
    disk.skills["race-pinned"].lastUsed = "2025-01-01T00:00:00.000Z";
    writeFileSync(statePath, `${JSON.stringify(disk, null, 2)}\n`);

    const staleCurator = new AutoSkillManager({ dir, mode: "manual", staleAfterDays: 1, archiveAfterDays: 2 });
    const pinner = new AutoSkillManager({ dir, mode: "manual" });
    pinner.execute({ action: "pin", name: "race-pinned" });
    expect(staleCurator.curate(Date.parse("2025-01-10T00:00:00.000Z"), { force: true }).archived).toEqual([]);
    expect(existsSync(join(dir, "race-pinned", "SKILL.md"))).toBe(true);
    expect(staleCurator.snapshot().skills["race-pinned"]).toMatchObject({ pinned: true, curatorState: "pinned" });
  });

  it("rejects live package drift instead of trusting stale in-memory metadata", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "drift-skill", description: "Drift", instructions });
    const skillPath = join(m.config.dir, "drift-skill", "SKILL.md");
    writeFileSync(skillPath, `${readFileSync(skillPath, "utf8")}\nexternal edit\n`);
    expect(() => m.execute({
      action: "patch",
      name: "drift-skill",
      instructions: `${instructions}\npatched`,
      expected_revision: created.revision,
    })).toThrow(/does not match history HEAD/);
    expect(readFileSync(skillPath, "utf8")).toContain("external edit");
  });

  it("rejects a tampered revision manifest even when its filename and HEAD are unchanged", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "history-skill", description: "History", instructions });
    const manifestPath = join(m.config.dir, ".history", "revisions", "history-skill", `${created.revision}.json`);
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    manifest.action = "tampered";
    chmodSync(manifestPath, 0o644);
    writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
    expect(() => m.execute({ action: "view", name: "history-skill" })).toThrow(/untrusted revision manifest/);
  });

  it("leaves the destination package unchanged when absorb staging fails", () => {
    const m = manager();
    const source: any = m.execute({ action: "create", name: "stage-source", description: "Source", instructions });
    const target: any = m.execute({ action: "create", name: "stage-target", description: "Target", instructions });
    const sourceRevision: any = m.execute({
      action: "write_file",
      name: "stage-source",
      file_path: "assets/collision",
      file_content: "source bytes",
      expected_revision: source.revision,
    });
    const targetHead: any = m.execute({
      action: "write_file",
      name: "stage-target",
      file_path: "assets/collision/keep.txt",
      file_content: "keep",
      expected_revision: target.revision,
    });
    expect(() => m.execute({
      action: "absorb_files",
      name: "stage-target",
      from_skill: "stage-source",
      file_paths: "assets/collision",
      expected_revision: targetHead.revision,
    })).toThrow();
    expect(readFileSync(join(m.config.dir, "stage-target", "assets", "collision", "keep.txt"), "utf8")).toBe("keep");
    expect(sourceRevision.revision).toMatch(/^[a-f0-9]{64}$/);
    expect(target.revision).toMatch(/^[a-f0-9]{64}$/);
  });

  it("rolls back a staged support write when revision publication fails", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "write-rollback", description: "Rollback", instructions });
    const skillPath = join(m.config.dir, "write-rollback", "SKILL.md");
    const files = Object.fromEntries([
      ["SKILL.md", digest(readFileSync(skillPath))],
      ["references/fail.txt", digest("new bytes")],
    ].sort(([a], [b]) => a.localeCompare(b)));
    const future = revisionId("write-rollback", created.revision, "write_file", files);
    writeFileSync(join(m.config.dir, ".history", "revisions", "write-rollback", `${future}.json`), "{}");

    expect(() => m.execute({
      action: "write_file",
      name: "write-rollback",
      file_path: "references/fail.txt",
      file_content: "new bytes",
      expected_revision: created.revision,
    })).toThrow(/untrusted revision manifest/);
    expect(existsSync(join(m.config.dir, "write-rollback", "references", "fail.txt"))).toBe(false);
    expect(readFileSync(join(m.config.dir, ".history", "heads", "write-rollback"), "utf8").trim()).toBe(created.revision);
  });

  it("rejects symlinks anywhere in a package before absorb or history mutation", () => {
    const m = manager();
    const source: any = m.execute({ action: "create", name: "link-source", description: "Source", instructions });
    const target: any = m.execute({ action: "create", name: "link-target", description: "Target", instructions });
    mkdirSync(join(m.config.dir, "link-source", "assets"), { recursive: true });
    writeFileSync(join(m.config.dir, "outside.bin"), "secret");
    symlinkSync(join(m.config.dir, "outside.bin"), join(m.config.dir, "link-source", "assets", "escape.bin"));
    expect(() => m.execute({
      action: "absorb_files",
      name: "link-target",
      from_skill: "link-source",
      expected_revision: target.revision,
    })).toThrow(/symlink/);
    // create → its unpublished absent "baseline" parent (history.go prepareMutationBase).
    expect(m.execute({ action: "history", name: "link-target" }).revisions.map((r: any) => [r.action, r.placement])).toEqual([["create", "active"], ["baseline", "absent"]]);
    expect(source.revision).toMatch(/^[a-f0-9]{64}$/);
  });

  it("refuses a pre-created skill-directory symlink without writing through it", () => {
    const m = manager();
    const outside = mkdtempSync(join(tmpdir(), "autogen-outside-"));
    symlinkSync(outside, join(m.config.dir, "redirected-skill"));
    expect(() => m.execute({
      action: "create",
      name: "redirected-skill",
      description: "Redirected",
      instructions,
    })).toThrow(/symlink/);
    expect(existsSync(join(outside, "SKILL.md"))).toBe(false);
  });

  it("rejects traversal forms and symlinked archive/history roots", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "bounded-skill", description: "Bounded", instructions });
    for (const file_path of ["../escape.txt", "/tmp/escape.txt", "assets\\..\\escape.txt"]) {
      expect(() => m.execute({
        action: "write_file",
        name: "bounded-skill",
        file_path,
        file_content: "escape",
        expected_revision: created.revision,
      }), file_path).toThrow();
    }

    const archiveOutside = mkdtempSync(join(tmpdir(), "autogen-archive-outside-"));
    symlinkSync(archiveOutside, join(m.config.dir, "archive"));
    expect(() => m.execute({
      action: "archive",
      name: "bounded-skill",
      expected_revision: created.revision,
      pruning_reason: "obsolete",
    })).toThrow(/symlink/);
    expect(existsSync(join(m.config.dir, "bounded-skill", "SKILL.md"))).toBe(true);
    expect(existsSync(join(archiveOutside, "bounded-skill"))).toBe(false);

    const historyManager = manager();
    const historyOutside = mkdtempSync(join(tmpdir(), "autogen-history-outside-"));
    mkdirSync(historyManager.config.dir, { recursive: true });
    symlinkSync(historyOutside, join(historyManager.config.dir, ".history"));
    expect(() => historyManager.execute({
      action: "create",
      name: "history-redirect",
      description: "History",
      instructions,
    })).toThrow(/symlink/);
    expect(existsSync(join(historyManager.config.dir, "history-redirect"))).toBe(false);
    expect(existsSync(join(historyOutside, "revisions"))).toBe(false);
  });

  it("rolls archive placement back when provenance publication fails", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "archive-rollback", description: "Archive", instructions });
    const manifest = JSON.parse(readFileSync(join(
      m.config.dir, ".history", "revisions", "archive-rollback", `${created.revision}.json`,
    ), "utf8"));
    const future = revisionId("archive-rollback", created.revision, "archive", manifest.files);
    writeFileSync(join(m.config.dir, ".history", "revisions", "archive-rollback", `${future}.json`), "{}");

    expect(() => m.execute({
      action: "archive",
      name: "archive-rollback",
      expected_revision: created.revision,
      pruning_reason: "obsolete",
    })).toThrow(/untrusted revision manifest/);
    expect(existsSync(join(m.config.dir, "archive-rollback", "SKILL.md"))).toBe(true);
    expect(existsSync(join(m.config.dir, "archive", "archive-rollback"))).toBe(false);
    expect(readFileSync(join(m.config.dir, ".history", "heads", "archive-rollback"), "utf8").trim()).toBe(created.revision);
  });

  it("does not restore an archived package when undo preconditions fail", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "archived-undo", description: "Archive", instructions });
    const archived: any = m.execute({
      action: "archive",
      name: "archived-undo",
      expected_revision: created.revision,
      pruning_reason: "obsolete",
    });
    expect(existsSync(archived.path)).toBe(true);
    expect(() => m.execute({
      action: "undo",
      name: "archived-undo",
      revision: created.revision,
      expected_revision: "0".repeat(64),
    })).toThrow(/revision conflict/);
    expect(existsSync(join(m.config.dir, "archived-undo"))).toBe(false);
    expect(existsSync(archived.path)).toBe(true);
  });

  it("restores an archived package through an ancestry-checked undo revision", () => {
    const m = manager();
    const created: any = m.execute({ action: "create", name: "archive-restore", description: "Archive", instructions });
    const archived: any = m.execute({
      action: "archive",
      name: "archive-restore",
      expected_revision: created.revision,
      pruning_reason: "temporarily obsolete",
    });
    expect(archived.revision).toMatch(/^[a-f0-9]{64}$/);
    const restored: any = m.execute({
      action: "undo",
      name: "archive-restore",
      revision: created.revision,
      expected_revision: archived.revision,
    });
    expect(restored.revision).toMatch(/^[a-f0-9]{64}$/);
    expect(existsSync(join(m.config.dir, "archive-restore", "SKILL.md"))).toBe(true);
    expect(existsSync(archived.path)).toBe(false);
    expect(m.snapshot().skills["archive-restore"]).toMatchObject({ archived: false, curatorState: "active" });
  });

  it("allows justified dropped files when archiving into an umbrella", () => {
    const m = manager();
    const source: any = m.execute({ action: "create", name: "drop-source", description: "Source", instructions });
    const target: any = m.execute({ action: "create", name: "drop-target", description: "Target", instructions });
    const written: any = m.execute({
      action: "write_file",
      name: "drop-source",
      file_path: "assets/obsolete.bin",
      file_content: "obsolete",
      expected_revision: source.revision,
    });
    const archived: any = m.execute({
      action: "archive",
      name: "drop-source",
      expected_revision: written.revision,
      absorbed_into: "drop-target",
      dropped_files: "assets/obsolete.bin",
      pruning_reason: "The artifact is obsolete and intentionally not retained.",
    });
    expect(archived.absorbed_into).toBe("drop-target");
    expect(target.revision).toMatch(/^[a-f0-9]{64}$/);
  });

  it("persists nudge cadence so session replay does not repeat a lifecycle nudge", () => {
    const entries: any[] = [];
    const first = new AutoSkillManager({
      dir: mkdtempSync(join(tmpdir(), "autogen-")),
      mode: "auto",
      nudgeInterval: 5,
      toolCallThreshold: 1,
    }, entry => entries.push({ type: "custom", customType: entry.type, data: entry.data }));
    first.observeTool(true, "read");
    expect(first.observeTurn()).toBeUndefined();
    for (let turn = 0; turn < 5; turn++) first.observeTurn();
    const emittedAt = first.snapshot().lastNudgeTurn;
    expect(emittedAt).toBeGreaterThan(0);

    const restored = manager({ nudgeInterval: 5, toolCallThreshold: 1 });
    restored.rehydrate(entries);
    expect(restored.snapshot().lastNudgeTurn).toBe(emittedAt);
    expect(restored.observeTurn()).toBeUndefined();
  });

  it("requires an auditable reason for a no-mutation review", () => {
    const m = manager();
    expect(() => m.execute({ action: "review" })).toThrow(/non-empty review_reason/);
    expect(m.execute({ action: "review", review_reason: "No reusable learning from this repository-specific check." }))
      .toMatchObject({ reviewed: true });
  });

  it("serializes skills across processes and recovers a dead lock owner", async () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-lock-"));
    const lock = join(dir, ".history", "locks", "locked-skill.lock");
    const childScript = `
      const fs = require("node:fs");
      const path = ${JSON.stringify(lock)};
      fs.mkdirSync(path, { recursive: true, mode: 0o700 });
      fs.writeFileSync(path + "/owner.json", JSON.stringify({
        pid: process.pid,
        token: "child-owner",
        createdAt: new Date().toISOString()
      }) + "\\n");
      process.stdout.write("held\\n");
      setInterval(() => {}, 1000);
    `;
    const child = spawn(process.execPath, ["-e", childScript], { stdio: ["ignore", "pipe", "inherit"] });
    await new Promise<void>((resolvePromise, reject) => {
      child.once("error", reject);
      child.stdout.once("data", () => resolvePromise());
    });
    const m = new AutoSkillManager({ dir, mode: "auto", lockTimeoutMs: 40 });
    try {
      expect(() => m.execute({
        action: "create",
        name: "locked-skill",
        description: "Locked",
        instructions,
      })).toThrow(/timed out waiting for skill mutation lock/);
      expect(m.execute({
        action: "create",
        name: "other-skill",
        description: "Other",
        instructions,
      }).revision).toMatch(/^[a-f0-9]{64}$/);
    } finally {
      child.kill("SIGKILL");
      await new Promise(resolvePromise => child.once("exit", resolvePromise));
    }
    expect(m.execute({
      action: "create",
      name: "locked-skill",
      description: "Recovered",
      instructions,
    }).revision).toMatch(/^[a-f0-9]{64}$/);
    expect(existsSync(lock)).toBe(false);
  });

  it("merges curator metadata under lock instead of losing another process update", () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-state-lock-"));
    const first = new AutoSkillManager({ dir, mode: "manual" });
    const second = new AutoSkillManager({ dir, mode: "manual" });
    first.execute({ action: "create", name: "first-skill", description: "First", instructions });
    second.execute({ action: "create", name: "second-skill", description: "Second", instructions });
    const reloaded = new AutoSkillManager({ dir, mode: "manual" });
    expect(Object.keys(reloaded.snapshot().skills).sort()).toEqual(["first-skill", "second-skill"]);
  });

  it("enforces read-only curator previews and view-before-write apply sessions", () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-scope-"));
    const owner = new AutoSkillManager({ dir, mode: "manual" });
    const created: any = owner.execute({ action: "create", name: "scoped-skill", description: "Scoped", instructions });

    const preview = new AutoSkillManager({ dir, mode: "manual", previewOnly: true });
    expect(preview.execute({ action: "view", name: "scoped-skill" }).revision).toBe(created.revision);
    expect(() => preview.execute({
      action: "patch", name: "scoped-skill", instructions, expected_revision: created.revision,
    })).toThrow(/preview is read-only/);

    const apply = new AutoSkillManager({ dir, mode: "manual", requireReadBeforeWrite: true });
    expect(() => apply.execute({
      action: "patch", name: "scoped-skill", instructions, expected_revision: created.revision,
    })).toThrow(/must be viewed/);
    const viewed: any = apply.execute({ action: "view", name: "scoped-skill" });
    expect(apply.execute({
      action: "patch", name: "scoped-skill", instructions: `${instructions}\nupdated`,
      expected_revision: viewed.revision,
    }).revision).toMatch(/^[a-f0-9]{64}$/);
  });

  it("shares pinned lifecycle protection with isolated curator processes", () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-state-"));
    const owner = new AutoSkillManager({ dir, mode: "manual" });
    owner.execute({ action: "create", name: "pinned-child", description: "Pinned", instructions });
    owner.execute({ action: "pin", name: "pinned-child" });

    const child = new AutoSkillManager({ dir, mode: "manual", requireReadBeforeWrite: true });
    const viewed: any = child.execute({ action: "view", name: "pinned-child" });
    expect(() => child.execute({
      action: "patch",
      name: "pinned-child",
      instructions: `${instructions}\nforbidden`,
      expected_revision: viewed.revision,
    })).toThrow(/pinned/);

    const preview = new AutoSkillManager({ dir, mode: "manual", previewOnly: true });
    const before = preview.snapshot();
    preview.execute({ action: "view", name: "pinned-child" });
    expect(preview.snapshot()).toEqual(before);
  });

  it("shares skill usage counters and timestamps across lifecycle observers", () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-usage-state-"));
    const owner = new AutoSkillManager({ dir, mode: "manual" });
    owner.execute({ action: "create", name: "usage-skill", description: "Usage", instructions });
    expect(owner.invokeSkill("usage-skill").skill).toBe("usage-skill");

    const observer = new AutoSkillManager({ dir, mode: "manual" });
    observer.observeTool(true, "SkillManage", { name: "usage-skill" });

    const reloaded = new AutoSkillManager({ dir, mode: "manual" });
    expect(reloaded.snapshot().skills["usage-skill"]).toMatchObject({
      uses: 2,
      curatorState: "active",
      archived: false,
    });
    expect(Date.parse(reloaded.snapshot().skills["usage-skill"].lastUsed ?? "")).not.toBeNaN();
  });

  it("runs semantic preview without mutation and preserves cadence on runner failure", async () => {
    const requests: any[] = [];
    const m = manager({
      curatorRunner: async (request: any) => {
        requests.push(request);
        return { output: "status: preview\nactions: []\nsummary: unchanged" };
      },
      curatorTimeoutMs: 1234,
      curatorMaxTurns: 4,
    });
    m.execute({ action: "create", name: "preview-skill", description: "Preview", instructions });
    const before = m.snapshot();
    const result = await m.runCurator({ preview: true, consolidate: true });
    expect(result).toMatchObject({ ran: true, preview: true, consolidated: false });
    expect(m.snapshot().curatorLastRun).toBe(before.curatorLastRun);
    expect(requests[0]).toMatchObject({ preview: true, consolidate: true, timeoutMs: 1234, maxTurns: 4 });
    expect(requests[0].prompt).toContain("status: preview|applied|unchanged|failed");
    expect(requests[0].prompt).toContain('"name": "preview-skill"');

    const failed = manager({ curatorRunner: async () => { throw new Error("runner failed"); } });
    const state = failed.snapshot();
    state.curatorLastRun = "2025-01-01T00:00:00.000Z";
    failed.restore(state);
    await expect(failed.runCurator({ consolidate: true, at: Date.parse("2025-02-01T00:00:00.000Z") }))
      .rejects.toThrow("runner failed");
    expect(failed.snapshot().curatorLastRun).toBe("2025-01-01T00:00:00.000Z");
  });

  it("suppresses duplicate curator runs and arms maintenance only while idle", async () => {
    let release!: () => void;
    const pending = new Promise<void>(resolvePromise => { release = resolvePromise; });
    let calls = 0;
    const m = manager({
      curatorRunner: async () => { calls++; await pending; return { output: "status: preview" }; },
      curatorIdleDelayMs: 10,
      curatorMinRunGapMs: 20,
    });
    const first = m.runCurator({ preview: true });
    const second = m.runCurator({ preview: true });
    expect(calls).toBe(1);
    release();
    await Promise.all([first, second]);

    vi.useFakeTimers();
    try {
      const scheduled = manager({ curatorIdleDelayMs: 10, curatorMinRunGapMs: 20 });
      const orchestrator = new CuratorOrchestrator(scheduled);
      orchestrator.idle();
      orchestrator.busy();
      await vi.advanceTimersByTimeAsync(20);
      expect(scheduled.snapshot().curatorLastRun).toBeUndefined();
      orchestrator.idle();
      await vi.advanceTimersByTimeAsync(10);
      expect(scheduled.snapshot().curatorLastRun).toBeDefined();
      orchestrator.dispose();
    } finally {
      vi.useRealTimers();
    }
  });

  it("suppresses curator runs shared by managers and a live external owner", async () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-run-lock-"));
    let release!: () => void;
    let started!: () => void;
    const pending = new Promise<void>(resolvePromise => { release = resolvePromise; });
    const running = new Promise<void>(resolvePromise => { started = resolvePromise; });
    let firstCalls = 0, secondCalls = 0;
    const first = new AutoSkillManager({
      dir, mode: "manual", lockTimeoutMs: 30,
      curatorRunner: async () => { firstCalls++; started(); await pending; return { output: "status: preview" }; },
    });
    const second = new AutoSkillManager({
      dir, mode: "manual", lockTimeoutMs: 30,
      curatorRunner: async () => { secondCalls++; return { output: "status: preview" }; },
    });
    const firstRun = first.runCurator({ preview: true });
    await running;
    const secondRun = second.runCurator({ preview: true });
    expect(firstCalls).toBe(1);
    expect(secondCalls).toBe(0);
    release();
    const [firstResult, secondResult] = await Promise.all([firstRun, secondRun]);
    expect(secondResult).toEqual(firstResult);

    const lock = join(dir, ".history", "locks", "curator-run.lock");
    const childScript = `
      const fs = require("node:fs");
      const path = ${JSON.stringify(lock)};
      fs.mkdirSync(path, { recursive: true, mode: 0o700 });
      fs.writeFileSync(path + "/owner.json", JSON.stringify({
        pid: process.pid, token: "curator-owner", createdAt: new Date().toISOString()
      }) + "\\n");
      process.stdout.write("held\\n");
      setInterval(() => {}, 1000);
    `;
    const child = spawn(process.execPath, ["-e", childScript], { stdio: ["ignore", "pipe", "inherit"] });
    await new Promise<void>((resolvePromise, reject) => {
      child.once("error", reject);
      child.stdout.once("data", () => resolvePromise());
    });
    try {
      await expect(first.runCurator({ preview: true })).resolves.toMatchObject({
        ran: false,
        reason: "already_running",
      });
      expect(firstCalls).toBe(1);
    } finally {
      child.kill("SIGKILL");
      await new Promise(resolvePromise => child.once("exit", resolvePromise));
    }
  });

  it("preserves fresh lifecycle metadata while seeding automatic cadence", async () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-seed-race-"));
    const owner = new AutoSkillManager({ dir, mode: "manual" });
    owner.execute({ action: "create", name: "seed-pinned", description: "Pinned", instructions });
    const staleAutomatic = new AutoSkillManager({ dir, mode: "manual" });
    const pinner = new AutoSkillManager({ dir, mode: "manual" });
    pinner.execute({ action: "pin", name: "seed-pinned" });
    await expect(staleAutomatic.runCurator({ automatic: true, at: Date.parse("2025-01-01T00:00:00.000Z") }))
      .resolves.toMatchObject({ ran: false, reason: "cadence_seeded" });
    const reloaded = new AutoSkillManager({ dir, mode: "manual" });
    expect(reloaded.snapshot().skills["seed-pinned"]).toMatchObject({ pinned: true, curatorState: "pinned" });
  });

  it("keeps curator maintenance and explicitly exempt child sessions outside the parent budget", async () => {
    const m = manager({ toolCallBudget: 1, staleAfterDays: 1, archiveAfterDays: 2 });
    const created: any = m.execute({ action: "create", name: "budget-archive", description: "Archive", instructions });
    m.observeTool(true, "TaskManage", { status: "in_progress", active: true });
    m.observeTool(true, "write");
    const state = m.snapshot();
    state.skills["budget-archive"].lastUsed = "2025-01-01T00:00:00.000Z";
    state.curatorLastRun = "2025-01-01T00:00:00.000Z";
    m.restore(state);
    writeFileSync(join(m.config.dir, ".history", "curator-state.json"), `${JSON.stringify({
      skills: state.skills,
      curatorLastRun: state.curatorLastRun,
      curatorLastReport: state.curatorLastReport,
    }, null, 2)}\n`);
    expect(m.curate(Date.parse("2025-01-10T00:00:00.000Z")).archived).toEqual(["budget-archive"]);
    expect(created.revision).toMatch(/^[a-f0-9]{64}$/);

    const handlers = new Map<string, Array<(event: any, ctx: any) => unknown>>();
    const exempt = registerAutoSkills({
      appendEntry() {},
      on(event: string, handler: (event: any, ctx: any) => unknown) {
        handlers.set(event, [...(handlers.get(event) ?? []), handler]);
      },
      registerTool() {},
    }, { mode: "auto", accountingExempt: true, dir: mkdtempSync(join(tmpdir(), "autogen-exempt-")) });
    await handlers.get("tool_result")![0]({ toolName: "write", input: { path: "x" }, isError: true }, {});
    expect(exempt.metrics()).toMatchObject({ toolCalls: 0, budgetCalls: 0, errors: 0 });
  });

  it("wires curator preview to an isolated SkillManage-only pi child", async () => {
    const dir = mkdtempSync(join(tmpdir(), "autogen-curator-adapter-"));
    const commands: any[] = [], execCalls: any[] = [], notifications: string[] = [];
    const pi = {
      appendEntry() {},
      on() {},
      registerTool() {},
      registerCommand(name: string, options: any) { commands.push({ name, options }); },
      async exec(command: string, args: string[], options: any) {
        execCalls.push({ command, args, options });
        return { stdout: "status: unchanged\nactions: []\nsummary: no changes", stderr: "", code: 0, killed: false };
      },
    };
    const m = registerAutoSkillsExtension(pi, { mode: "auto", dir, curatorTimeoutMs: 4321 });
    m.execute({ action: "create", name: "adapter-skill", description: "Adapter", instructions });
    const command = commands.find(entry => entry.name === "curator");
    await command.options.handler("preview", { ui: { notify: (message: string) => notifications.push(message) } });

    expect(execCalls).toHaveLength(1);
    expect(execCalls[0]).toMatchObject({ command: "env", options: { timeout: 4321 } });
    expect(execCalls[0].args).toEqual(expect.arrayContaining([
      "SWARM_AUTOGEN_MODE=manual",
      "SWARM_AUTOGEN_PREVIEW=1",
      "SWARM_AUTOGEN_REQUIRE_VIEW=1",
      "SWARM_AUTOGEN_ACCOUNTING_EXEMPT=1",
      "SWARM_CURATOR_CHILD=1",
      "--no-extensions",
      "--tools",
      "SkillManage",
    ]));
    expect(notifications.at(-1)).toContain("status: unchanged");
  });

  it("shares the concrete default autogen directory with curator children", async () => {
    const home = mkdtempSync(join(tmpdir(), "autogen-default-home-"));
    const commands: any[] = [], execCalls: any[] = [];
    vi.stubEnv("HOME", home);
    vi.stubEnv("SWARM_AUTOGEN_DIR", "");
    try {
      const pi = {
        appendEntry() {},
        on() {},
        registerTool() {},
        registerCommand(name: string, options: any) { commands.push({ name, options }); },
        async exec(command: string, args: string[], options: any) {
          execCalls.push({ command, args, options });
          return { stdout: "status: unchanged\nactions: []\nsummary: no changes", stderr: "", code: 0, killed: false };
        },
      };
      const manager = registerAutoSkillsExtension(pi, { mode: "auto" });
      const expected = join(home, ".swarm", "skills", "autogen");
      expect(manager.config.dir).toBe(expected);
      await commands.find(entry => entry.name === "curator").options.handler("preview", {
        ui: { notify() {} },
      });
      expect(execCalls[0].args).toContain(`SWARM_AUTOGEN_DIR=${expected}`);
      expect(execCalls[0].args).not.toContain("SWARM_AUTOGEN_DIR=");
    } finally {
      vi.unstubAllEnvs();
    }
  });
});
