import { describe, expect, it } from "vitest";
import { AutoSkillManager } from "../src/index.js";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const instructions = "A reusable production procedure. ".repeat(8);
const manager = (extra = {}) => new AutoSkillManager({ dir: mkdtempSync(join(tmpdir(), "autogen-")), mode: "auto", ...extra });

describe("autogenerated skills", () => {
  it("defaults to safe never mode and validates exact modes", () => {
    expect(new AutoSkillManager({ dir: "/tmp/x" }).config.mode).toBe("never");
    expect(new AutoSkillManager({ mode: "auto" }).config.toolCallBudget).toBe(5);
    expect(new AutoSkillManager({ mode: "auto" }).config.workingBudget).toBe(90);
    expect(() => new AutoSkillManager({ mode: "invalid" as any })).toThrow(/invalid autogen mode/);
  });
  it("tracks metrics, revisions, review hooks, and pinning", () => {
    const events: any[] = [], m = manager({ reviewHook: e => events.push(e) });
    const created: any = m.execute({ action: "create", name: "build-check", description: "Build checks", instructions });
    expect(created.revision).toMatch(/^[a-f0-9]{64}$/);
    expect(m.execute({ action: "metrics" }).metrics.mutations).toBe(1);
    expect(m.execute({ action: "pin", name: "build-check" }).state).toBe("pinned");
    expect(() => m.execute({ action: "archive", name: "build-check" })).toThrow(/pinned/);
    expect(events.map(e => e.action)).toEqual(["create", "pin"]);
  });
  it("rejects stale mutations until a review and supports expected revisions", () => {
    const m = manager({ toolCallBudget: 1 });
    m.observeTool(true, "bash");
    expect(() => m.execute({ action: "create", name: "too-late", description: "x", instructions })).toThrow(/budget/);
  });
  it("rehydrates the complete budget state from Pi session entries", () => {
    const entries: any[] = [];
    const first = new AutoSkillManager({ dir: mkdtempSync(join(tmpdir(), "autogen-")), mode: "auto" }, (entry: any) => entries.push(entry));
    first.observeTool(true, "bash", { command: "node build" });
    first.observeTool(false, "write", { path: "x" });
    const before = first.snapshot();
    const restored = manager();
    restored.rehydrate(entries);
    expect(restored.snapshot()).toMatchObject({
      toolCalls: before.toolCalls,
      budgetCalls: before.budgetCalls,
      errors: before.errors,
      skilled: before.skilled,
      reviewRequired: before.reviewRequired,
    });
  });
  it("hard-blocks onboarding calls and escalates working-tier nudges", () => {
    const onboarding = manager({ toolCallBudget: 1 });
    onboarding.observeTool(true, "bash");
    expect(onboarding.gateTool("write", { path: "x" })).toMatchObject({ block: true });

    const working = manager({ toolCallBudget: 1, workingBudget: 2, maxNudgeIgnores: 2 });
    working.observeTool(true, "Skill", { skill: "external-skill" });
    working.observeTool(true, "write");
    working.observeTool(true, "write");
    expect(working.gateTool("write")).toMatchObject({ message: expect.stringContaining("review") });
    expect(working.gateTool("write")).toMatchObject({ message: expect.stringContaining("review") });
    expect(working.gateTool("write")).toMatchObject({ block: true, reason: expect.stringContaining("review required") });
  });
});
