// Code generated by cmd/shimgen; DO NOT EDIT.

// Package gemini is a compatibility shim.
//
// Deprecated: the implementation moved to internal/provider/gemini. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package gemini

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/provider/gemini"
)

type AuthMode = ipkg.AuthMode
type CachedContent = ipkg.CachedContent
type Candidate = ipkg.Candidate
type Config = ipkg.Config
type Content = ipkg.Content
type CreateCachedContentRequest = ipkg.CreateCachedContentRequest
type CreateCachedContentResponse = ipkg.CreateCachedContentResponse
type FunctionCall = ipkg.FunctionCall
type FunctionCallingConfig = ipkg.FunctionCallingConfig
type FunctionDeclaration = ipkg.FunctionDeclaration
type FunctionResponse = ipkg.FunctionResponse
type GeminiErrorResponse = ipkg.GeminiErrorResponse
type GeminiRequest = ipkg.GeminiRequest
type GeminiResponse = ipkg.GeminiResponse
type GeminiTokenSource = ipkg.GeminiTokenSource
type GenerationConfig = ipkg.GenerationConfig
type InlineData = ipkg.InlineData
type ListCachedContentsResponse = ipkg.ListCachedContentsResponse
type OAuthManager = ipkg.OAuthManager
type OAuthTokens = ipkg.OAuthTokens
type Part = ipkg.Part
type Provider = ipkg.Provider
type SSEClient = ipkg.SSEClient
type SafetyRating = ipkg.SafetyRating
type SafetySetting = ipkg.SafetySetting
type StreamAccumulator = ipkg.StreamAccumulator
type ThinkingConfig = ipkg.ThinkingConfig
type Tool = ipkg.Tool
type ToolConfig = ipkg.ToolConfig
type UsageMetadata = ipkg.UsageMetadata
type VertexRequest = ipkg.VertexRequest
type VertexResponse = ipkg.VertexResponse

const AuthModeADC = ipkg.AuthModeADC
const AuthModeAPIKey = ipkg.AuthModeAPIKey
const AuthModeOAuth = ipkg.AuthModeOAuth
const DefaultAPIVersion = ipkg.DefaultAPIVersion
const DefaultBaseURL = ipkg.DefaultBaseURL
const DefaultClientID = ipkg.DefaultClientID
const DefaultClientSecret = ipkg.DefaultClientSecret
const SyntheticThoughtSignature = ipkg.SyntheticThoughtSignature

var DefaultScopes = ipkg.DefaultScopes

var ErrRefreshTokenInvalid = ipkg.ErrRefreshTokenInvalid

var HasStoredOAuthToken = ipkg.HasStoredOAuthToken
var IsMessageValid = ipkg.IsMessageValid
var IsReauthRequired = ipkg.IsReauthRequired
var MustRegister = ipkg.MustRegister
var New = ipkg.New
var NewDefault = ipkg.NewDefault
var NewOAuthManager = ipkg.NewOAuthManager
var NewSSEClient = ipkg.NewSSEClient
var NewStreamAccumulator = ipkg.NewStreamAccumulator
var NewWithAPIKey = ipkg.NewWithAPIKey
var NewWithOAuth = ipkg.NewWithOAuth
var ParseGeminiError = ipkg.ParseGeminiError
var Register = ipkg.Register
var RegisterWithConfig = ipkg.RegisterWithConfig
var SanitizeMessage = ipkg.SanitizeMessage
var SanitizeMessages = ipkg.SanitizeMessages
var TranslateRequest = ipkg.TranslateRequest
var TranslateResponse = ipkg.TranslateResponse
var WithBaseURL = ipkg.WithBaseURL
var WithModel = ipkg.WithModel
var WithNoBrowser = ipkg.WithNoBrowser
var WithProjectID = ipkg.WithProjectID
var WithTimeout = ipkg.WithTimeout
var WithTokenPath = ipkg.WithTokenPath
