package vocab

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// These artifacts are generated by scripts/vocab/train_artifact.py from the
// weekly matched-corpus analysis. Embedding gives every binary a known baseline;
// deployments may override it with Load(path) without rebuilding.
//
//go:embed artifacts/prose.json
var embeddedProse []byte

//go:embed artifacts/thinking.json
var embeddedThinking []byte

// Embedded loads the checked-in artifact for prose or thinking.
func Embedded(channel string) (*Scorer, error) {
	var raw []byte
	switch channel {
	case "prose":
		raw = embeddedProse
	case "thinking":
		raw = embeddedThinking
	default:
		return nil, fmt.Errorf("unknown vocabulary channel %q", channel)
	}
	var art Artifact
	if err := json.Unmarshal(raw, &art); err != nil {
		return nil, fmt.Errorf("parse embedded %s artifact: %w", channel, err)
	}
	if art.Schema != 1 {
		return nil, fmt.Errorf("unsupported embedded %s schema %d", channel, art.Schema)
	}
	return New(art), nil
}
