// Code generated by cmd/shimgen; DO NOT EDIT.

// Package interaction is a compatibility shim.
//
// Deprecated: the implementation moved to internal/interaction. New code should use
// the client facade (github.com/Swarm-Code/mono/swarm-sdk/client).
package interaction

import (
	ipkg "github.com/Swarm-Code/mono/swarm-sdk/internal/interaction"
)

type ApprovalContext = ipkg.ApprovalContext
type ApprovalDecision = ipkg.ApprovalDecision
type ApprovalPreview = ipkg.ApprovalPreview
type ApprovalRequest = ipkg.ApprovalRequest
type ApprovalResponse = ipkg.ApprovalResponse
type ApprovalScope = ipkg.ApprovalScope
type AsyncBroker = ipkg.AsyncBroker
type BrokerAdapter = ipkg.BrokerAdapter
type MockBroker = ipkg.MockBroker
type Notification = ipkg.Notification
type NotificationLevel = ipkg.NotificationLevel
type QuestionMetadata = ipkg.QuestionMetadata
type QuestionnaireAnswer = ipkg.QuestionnaireAnswer
type QuestionnaireQuestion = ipkg.QuestionnaireQuestion
type QuestionOption = ipkg.QuestionOption
type QuestionRequest = ipkg.QuestionRequest
type QuestionResponse = ipkg.QuestionResponse
type QuestionType = ipkg.QuestionType
type UserInteractionBroker = ipkg.UserInteractionBroker

const ApprovalApprove = ipkg.ApprovalApprove
const ApprovalCancel = ipkg.ApprovalCancel
const ApprovalDeny = ipkg.ApprovalDeny
const ApprovalScopeAlways = ipkg.ApprovalScopeAlways
const ApprovalScopeOnce = ipkg.ApprovalScopeOnce
const ApprovalScopeSession = ipkg.ApprovalScopeSession
const NotificationError = ipkg.NotificationError
const NotificationInfo = ipkg.NotificationInfo
const NotificationSuccess = ipkg.NotificationSuccess
const NotificationWarning = ipkg.NotificationWarning
const QuestionTypeChoice = ipkg.QuestionTypeChoice
const QuestionTypeConfirm = ipkg.QuestionTypeConfirm
const QuestionTypeMultiChoice = ipkg.QuestionTypeMultiChoice
const QuestionTypeNumber = ipkg.QuestionTypeNumber
const QuestionTypeQuestionnaire = ipkg.QuestionTypeQuestionnaire
const QuestionTypeText = ipkg.QuestionTypeText
const QuestionTypeVisualChoice = ipkg.QuestionTypeVisualChoice

var ErrAsyncBrokerUnsupported = ipkg.ErrAsyncBrokerUnsupported

var NewBrokerAdapter = ipkg.NewBrokerAdapter
var NewMockBroker = ipkg.NewMockBroker
